### ISSUE TITLE
Use `except: [...]` to exclude attributes for actions that do not require a complete attribute set

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#1001]
*Update title after finding a workable solution*

Would like more control over what attributes are sent back for each endpoint. The first use case would be limiting the number of attributes sent back for lists. Lists, in most cases, could use a subset of a models attributes.

Either add an use `*CollectionSerializer` serializers, or discover a way to customize the attributes another way using existing serializers, or something else.

**Comment by stackus** [comment]
We can customize the output of actions by using the `except: [{...attributes array...}]` to exclude attributes when not needed. Add these as `{action}_respond_options` methods and then use them like the example below.

```ruby
def index
  authorize Product
  respond_with_params products, index_respond_options
end

private

def index_respond_options
  { each_serializer: ProductSerializer, except: [:order_questions, :active, :deleted_at] }
end
```

**Comment by stackus** [comment]
@voxlol Pair with @AnkyrinRepeat on this task.

**Comment by AnkyrinRepeat** [comment]
We added excludes for Projects, Orders, Services, and Marketplace. They still all have an array/object called Products that is being added by 

```function resolveOrders(Order) {
    return Order.query({'includes[]': ['staff', 'project', 'product']}).$promise;
  }```

that includes redundant information. @stackus should we try to prune that as well or leave it?

**Comment by stackus** [comment]
Should only add excludes for attributes, not relationships. I suspect you've added an exclude for a relationship and that's why you're seeing an empty array.
