### ISSUE TITLE
Need phone field validation on user forms

### ISSUE THREAD

**Issue by voxlol** [projectjellyfish/api#1034]
Right now there are no validations for phone numbers, and they are stored as a string up to 30 characters in the DB. I could enter "hello" on the form and it'll be saved in the DB because there's no validation at the moment

**Comment by AnkyrinRepeat** [comment]
I think leaving the phone number unvalidated may be the best option. Then we don't need to worry about accommodating international formatting (+33 1 23 45 67 89) or extensions ( 512-123-4567 ext: 4444). 

If we are going to validate numbers, should we assume only US phone number with no extension?

**Comment by stackus** [comment]
I suggest you use a simple pattern match for the field on both the client and server. Google for one.
