### ISSUE TITLE
Services need records of logs and errors

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#1037]
During the provisioning process it's possible some important messaging or errors might be returned by the provider or client and we should record these messages.

These logs should be readonly, and they don't need any methods or interfaces for a user to create them.

- [x] Store messages, record log level and timestamp
- [x] Display messages on the service details page
- [ ] Paginate results for UX and sort by newest first

**Comment by AllenBW** [comment]
Is this an object, possibly titled *logs* we want to append to `/api/v1/services/:id ` ?
Or is this a new endpoint `/api/v1/logs/:serviceid` (except it would just be id) ? 

d

**Comment by stackus** [comment]
Each log should be a record in the database and should be associated with a `Service` as a `has_many` relationship. Since it won't be much trouble we can make that relationship polymorphic so other things can have logs attached to them.

The endpoint to get the logs should be scoped to the service so either of the following could work (the second only if the polymorphic route is taken.)

- `/api/v1/services/:id/logs?page=:page&per_page=:per_page`
- `/api/v1/logs/:logableType/:logableId?page=:page&per_page=:per_page`

**Comment by voxlol** [comment]
PR #1068 resolves everything except for server-side pagination of the Service logs

There's a compatibility problem between Serializer root being false and attaching log meta information (current page, next page, total logs, etc) to a request response.

**Comment by stackus** [comment]
Sadly, yes. Getting meta information into the responses would be really helpful and useful in a lot more places than just pagination results.

Off the top of my head adding roots would require
- using a different services library (maybe Restangular?) in UX
- updating every resource in UX
