### ISSUE TITLE
Cannot access or display service outputs

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#1038]
Service may have many outputs created by the provisioning process or by other actions taken on a service.

- [x] Endpoint or accessible method for `service_outputs`
- [x] Display outputs on the service details page

**Comment by AllenBW** [comment]
Is there any standardized form or common qualities we can expect of output?

Leaning towards the latter implementation suggestion for fear of becoming endpoint/join crazy.

**Comment by stackus** [comment]
Service outputs work like answers and settings where they all have content types.
