### ISSUE TITLE
Services cannot be 'deprovisioned' 

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#1039]
Services should have a counterpart action to `provision` to deprovision a service. Deprovisioning a service should be handled by the same class that provisioned the service.

- [ ] Add deprovision method
- [ ] Add action to UX

**Comment by AllenBW** [comment]
Permission to hijack DELETE for this purpose?

**Comment by stackus** [comment]
Nope, this should be an 'action'. It'll be the first of many actions.

**Comment by AllenBW** [comment]
An action in the service_controller?  Or should deprovision, be a full on use_case (as there are many pieces that might need to be halted when deprovisioning a service).

**Comment by stackus** [comment]
I meant like starting, stopping, doing foo, or toggling bar.

Core only needs to have the parts necessary to call the action. the work of the action itself will be up to the custom product and service classes.
