### ISSUE TITLE
Site has issues in IE

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#1053]
Open the calendar for either `start_date` or `end_date` on the 'Create Project' page. Clicking a date or done does not close the popup.

- [ ] The calendar widget won't close once it has been expanded on an input when viewed in IE
- [ ] Tag input does not allow more than one tag to be entered in IE

**Comment by AllenBW** [comment]
Emulated modes from IE8 to 11 in microsoft edge do not produce any issues (so we aren't relying on that method of testing).

VMs running native browser version on heroku demo site.

IE8 WIN7 (emulated) - unable to log in

IE9 WIN7 - ```SEC7111: https security is compromised by http://jellyfish-demo.herokuapp.com/images/jellyfish_main_logo.png```  unable to log in

IE10 WIN7 -
* project.edit state, able to select date, upon selecting datepicker does not close, when selecting done, datepicker does not close, when selecting original input field or calendar icon (after selecting a date), datepicker **does** close.  Issue partially confirmed. 
* manage.product.edit state, able to add multiple tags using autocomplete and tag wizard. marketplace state, able to add multiple tags using autocomplete and tag wizard. manage.product-categories.edit state, able to add multiple tags using autocomplete and tag wizard.

**Comment by AllenBW** [comment]
Tag select issue was not reproducible, screen shot of proper function below.

![ie 10 win7](https://cloud.githubusercontent.com/assets/6640236/11073034/a87060de-87b6-11e5-90fb-214c8a5c120e.png)

Datepicker issue was reproducible,  incoming pr fixes the issue as described and observed.
