### ISSUE TITLE
Improve project budget reporting

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#1064]
Belongs to #1061 

Projects allow the setting of a project budget only. They should allow for a monthly budget as well so that budget overruns can be better reported.

Also the processes required to keep the projects budget usage needs to be updated too. Are there other options other than using Cron to keeping this data fresh? Can it be done in a lazy fashion?

**Comment by AllenBW** [comment]
Would like to suggest instead of locking ourselves into specifically monthly budgets, we should perhaps look into budget over any number amount of days (it could be a week, it could be a month, it could be three weeks, two weeks).

**Comment by stackus** [comment]
We could do this, the `hourly_price` could work for us allowing us to do 24 * 7, or whatever but adding that would require the issue to be resized and scoped.

We could design, in a separate issue, a dashboard widget that display information about budgets in various spans of time.

**Comment by voxlol** [comment]
@stackus Just to clarify,

`monthly_spend` is the sum of the monthly cost of active services in a project

`monthly_budget` will be a new column that will trigger alerts if, for example, `monthly_spend` > `monthly_budget`

There should also be a new column `monthly_spent` that is the total amount of money spent this current month (which should be the same as `monthly_spend` but also includes installation fees). Does this sound right? Or is it too similar to `monthly_spend` to warrant creation?

**Comment by stackus** [comment]
Would need to do the check for being over budget prior to completing the order, you may have meant that but wanted to be clear.

Not sure if a `monthly_spent` column would help us much. When an order is completed the `setup_price` should be added to `budget_spent`, and the `monthly_cost` added to the `monthly_spend`. Then once a month the `monthly_spend` is added to `budget_spent`.

That I think covers most things. On the flip side when a service is deprovisioned its `monthly_cost` is subtracted from `monthly_spend`. Mentioning this for fyi, don't think you'll be doing any deprovisioning updates.
