### ISSUE TITLE
UX needs 508 compliance

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#1072]
We need to ensure that the current Jellyfish UX is 508 compliant.  This is a high priority.  This should help with that task:

http://www.508checker.com/what-is-508-compliance

@stackus we need to prioritize this ASAP.

**Comment by stackus** [comment]
There is an Angular module `ngAria`\* that can help you accomplish a majority of the compliance.

*: It may not be installed.

**Comment by voxlol** [comment]
Added ngAria which helped a lot.

Also, just stumbled upon https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb?hl=en which lets you run accessibility audits from the developer tools (and made by Google).

**Comment by sonejah21** [comment]
*I'll be working on this ticket in tandem with @voxlol

**Comment by sonejah21** [comment]
The following are screenshots of the blue colors in the application. 

BEFORE:
The first couple of screenshots are examples of the original shade of `$app-color-blue` for Project Jellyfish which has a hex code of `#3397DB` &  `hsla(204, 70%, 53%, 1)`. It has a contrast ratio of 3.2.
<img width="1430" alt="screen shot 2015-12-01 at 1 11 53 pm" src="https://cloud.githubusercontent.com/assets/5269893/11509724/c2099f42-982d-11e5-889a-89fdcbbf840a.png">
<img width="1430" alt="screen shot 2015-12-01 at 1 12 09 pm" src="https://cloud.githubusercontent.com/assets/5269893/11509725/c20e512c-982d-11e5-800e-090e51b0950a.png">

**Comment by sonejah21** [comment]
AFTER 

Option #1:
`$app-color-dark-blue` = `#3272db` & `hsla(217, 70%, 53%, 1)`. Contrast ratio: 4.6. *This is just above the threshold of 4.5 required for compliance.

<img width="1430" alt="screen shot 2015-12-01 at 1 19 41 pm" src="https://cloud.githubusercontent.com/assets/5269893/11509856/97d1f52a-982e-11e5-8d95-bdaf7eb22c5a.png">
<img width="1429" alt="screen shot 2015-12-01 at 1 19 49 pm" src="https://cloud.githubusercontent.com/assets/5269893/11509855/97cfd74a-982e-11e5-9ce6-2fe0306eeb65.png">

**Comment by sonejah21** [comment]
Option B: 

Barely lighter than the above, but an even closer tint to the original. I am leaning toward this one. 
`$app-color-dark-blue` = `#3374db`& `hsla(217, 70%, 53%, 1)`. Contrast ratio: 4.5.

<img width="1418" alt="screen shot 2015-12-01 at 1 28 05 pm" src="https://cloud.githubusercontent.com/assets/5269893/11510021/7d4700b4-982f-11e5-8b23-b2d703f514a3.png">
<img width="1425" alt="screen shot 2015-12-01 at 1 28 22 pm" src="https://cloud.githubusercontent.com/assets/5269893/11510022/7d558fbc-982f-11e5-90b2-2634005131e8.png">

**Comment by AllenBW** [comment]
I dig da B.

**Comment by sonejah21** [comment]
@AllenBW what about the last option? I had liked B, but then I discovered the beauty of C. It's quite close to the original color blue we have, just a bit darker. It is quite subdued though.

**Comment by AllenBW** [comment]
@sonejah21 previous love withstands the coming of c.  it has just that little bit of "pop" that calls attention to actions and the logo

**Comment by mafernando** [comment]
I kind of like option B as well, C might be too subtle for my liking.

**Comment by stackus** [comment]
I like the blue from option C it appears to have changed the least. Did the green change a lot too as well? It looks like a forest green now.

**Comment by sonejah21** [comment]
I didn't change the green, but I'll create some green options and do the same as above.

**Comment by AnkyrinRepeat** [comment]
My vote is for C.

**Comment by voxlol** [comment]
I like the light blue in B. My vote for B

**Comment by stackus** [comment]
@sonejah21 : *nod*, then I blame the blue and 508 in general.

**Comment by sonejah21** [comment]
The green was in fact changed to a darker green from the original, so let's see if we can find a closer shade to what we're used to:

BEFORE

$app-color-green: `#1dc58e`


<img width="355" alt="screen shot 2015-12-01 at 5 48 55 pm" src="https://cloud.githubusercontent.com/assets/5269893/11516820/d6b0bd24-9853-11e5-81b3-c9c97da143c6.png">

**Comment by sonejah21** [comment]
AFTER

Option A: 
This is the closest to the original that is 508 Compliant. It has a contrast ratio of 4.5 and only the lightness was tweaked.

It is `#1d8668` & `hsla(163, 64%, 32%, 1)`.

<img width="361" alt="screen shot 2015-12-01 at 5 45 16 pm" src="https://cloud.githubusercontent.com/assets/5269893/11516920/74e298d2-9854-11e5-8730-81d4632a776a.png">

**Comment by sonejah21** [comment]
OPTION B:

Another option that is a variation on lightness of the $app-color-green. It is slightly more jungle green than the above. Contrast ratio is at 4.6.

It is `#14855f` & `hsla(160, 74%, 30%, 1)`.

<img width="397" alt="screen shot 2015-12-01 at 5 58 44 pm" src="https://cloud.githubusercontent.com/assets/5269893/11517089/6c6bec7a-9855-11e5-8a53-672abc94bbb5.png">
