### ISSUE TITLE
Create User/Staff form not properly validating

### ISSUE THREAD

**Issue by voxlol** [projectjellyfish/api#1088]
If I navigate to the User create form and click submit on an empty form, a POST request is sent to the server despite being invalid. The form validation is having issues...`vm.form.$invalid` is not being marked as true on an invalid form.

![screen shot 2015-12-03 at 9 14 32 am](https://cloud.githubusercontent.com/assets/11891171/11564344/5292ab8c-999e-11e5-8b4b-ccb5c6094260.png)

![screen shot 2015-12-03 at 9 14 46 am](https://cloud.githubusercontent.com/assets/11891171/11564347/54e4269a-999e-11e5-8ad7-f3940fe201e3.png)

**Comment by AllenBW** [comment]
was an issue with phone number validation, formly wants a response on validation or ELSE

<img width="1088" alt="screen shot 2015-12-03 at 1 39 57 pm" src="https://cloud.githubusercontent.com/assets/6640236/11570129/9e95b8d8-99c3-11e5-906a-3176c1ba3689.png">
