### ISSUE TITLE
Theming : Settings can be changed

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#1090]
The settings that make up a theme can be loaded, changed, and saved back to the server.

* As a manager I can update the application theme

  - [ ] Colors can be set
  - [ ] ~~Brand image can be set~~ Moved to next sprint.
  - [ ] Theme can be undone

Belongs to #1067

**Comment by voxlol** [comment]
I thought image configuration in themes was going to be for the next sprint, or do you want the brand image to be set in this issue?

**Comment by AllenBW** [comment]
amirite? http://angular-formly.com/#/example/integrations/colorpicker
