### ISSUE TITLE
Add tagging to servers, projects, and users

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#110]
Add tagging to servers, projects, and users

**Comment by mafernando** [comment]
Checking out [this](http://railscasts.com/episodes/382-tagging?view=asciicast) railscast on tagging.

**Comment by mafernando** [comment]
Potential candidate, [acts-as-taggable-on](https://github.com/mbleigh/acts-as-taggable-on).

**Comment by mafernando** [comment]
Per Chris K, make the following models taggable:
 - [ ] Projects
 - [ ] Products
 - [ ] Staff
 - [ ] Order
 - [ ] OrderItems
 - [ ] ContentPages
 - [ ] Bundles
 - [ ] Alerts

**Comment by mafernando** [comment]
We should address what happens if a record is deleted - do its associated tags become orphans?

Should we periodically flush orphans?

**Comment by chriskacerguis** [comment]
I would just leave them.  The UX will auto-complete existing ones, so I don't think it's a big deal.

**Comment by mafernando** [comment]
PR is open and documentation can be found [here](https://github.com/projectjellyfish/api/wiki/Tags-in-Project-Jellyfish).
