### ISSUE TITLE
Build out services controller API endpoints

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#116]
Need API to show all servers.  This would be for an admin to see everything.

**Comment by mafernando** [comment]
Would be nice to use `/services/tag` as a way to retrieve resources.

**Comment by mafernando** [comment]
Currently working on this in the [enhancement/ux-477-add-servers-to-sidebar](https://github.com/projectjellyfish/api/compare/) branch.
- [x] add /services routes to API
- [ ] add /services/tag route

**Comment by mafernando** [comment]
Right now `/services` and `/services/:tag` are returning services as order items with order item attributes. 

Problematically, we don't have things like Product Type or other attributes regarding the Project/Order the OrderItem lives on.

I know that we are currently leveraging serializers in Jellyfish, so I'm looking at setting one up for services.

**Comment by mafernando** [comment]
Couldn't figure out how to attach project/product attributes to OrderItems using scope since Service is handled from its own model. I took the approach of overriding the default select clause that comes with ActiveRecord so that I could select multiple attributes across table joins.

**Comment by mafernando** [comment]
I have built out the ServicesController the following endpoints: 
 - [\services](https://github.com/projectjellyfish/api/blob/enhancement/ux-477-add-servers-to-sidebar/app/controllers/services_controller.rb#L4-L9): returns a list of order_items and details about their associated project and product
 - [\services\count](https://github.com/projectjellyfish/api/blob/enhancement/ux-477-add-servers-to-sidebar/app/controllers/services_controller.rb#L11-L24): returns a summary view of order_items per project and an overall summary of distinct order items across all projects. 
 - [\services\:tag](https://github.com/projectjellyfish/api/blob/enhancement/ux-477-add-servers-to-sidebar/app/controllers/services_controller.rb#L26-L31): returns a list of order_items tagged with `:tag` and details about their associated project and product

**Comment by mafernando** [comment]
Haved moved aforementioned changes into [this](https://github.com/projectjellyfish/api/tree/feature/add-services-api) branch.
