### ISSUE TITLE
Move ProductTypes to JSON files

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#121]
For more portability and some upcoming changes, we need to move the data from the ProductTypes to JSON files.

These should be stored in:

config/mods/:mod_name/product_types/:product_type.json

There could be one or more product types in that DIR.

**Comment by OBCENEIKON** [comment]
Adding to backlog for now until Monday when we discuss with Thoughtbot.

**Comment by calebthompson** [comment]
This will be handled elsewhere as a side-effect.
