### ISSUE TITLE
Alerts API needs to not use auth, and just use an API key

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#124]
Alerts API needs to not use auth, and just use an API key

**Comment by mafernando** [comment]
TODO: Determine if we need to work out logic to map services from Sensu to their corresponding order items to address this issue correctly.

## POST Params for Sensu Alerts
| Attribute  | Description  |     
|:------------- |:------------- |
| hostname | name of host service is on |
| port | port that the service is accessible on the host from |
| service | name of the service |
| status | _Current Options: OK, WARNING, CRITICAL, UNKNOWN, PENDING_  |
| message | message accompanying alert |
| event | addl string that can be passed back  |

## Alerts Schema
| Attribute  | Description  |     
|:------------- |:------------- |
| id | auto-incremented unique key  |
| project_id | id of project this alert is associated with  |
| staff_id | id of staff who posted this alert |
| status | [project defined enum](https://github.com/projectjellyfish/api/blob/master/app/models/project.rb#L50)  |
| message | alert message |
| start_date | when the alert is scheduled to begin appearing |
| end_date | when the alert should stop appearing |
| created_at | when the alert was created |
| updated_at | when the alert as last updated |
| order_item_id | id of order item (a.k.a. service) associated with alert |

**Comment by mafernando** [comment]
Posting Alerts from Sensu should be fine. 

Changes I made were put in PR https://github.com/projectjellyfish/api/pull/535. _(merged)_

**Follow-Up**: Need to create a data store that will allow us to map _host_, _port_, and _service name_ from Sensu to their corresponding _service/order_item_ in `/api`. At this point, I think we should review the [`payloads`](https://github.com/projectjellyfish/api/blob/master/db/schema.rb#L178-L180) being exchanged during provisioning and determine how to build out this piece. 

**Workflow**:
 1. Sensu/Staff signs in and obtains an api_token.
 2. Subsequent request from the Sensu/Staff passes `X-Staff-Token` and `X-Staff-Email` to API along with the POST params for a Sensu Alert 

  | Attribute  | Description | Required |     
|:------------- |:------------- |:------------- | 
| host | name of host service is on | YES |
| port | port that the service is accessible on the host from | YES |
| service | name of the service | YES |
| status | [OK, WARNING, CRITICAL, UNKNOWN, PENDING] => [defined here](https://github.com/projectjellyfish/api/blob/master/app/models/project.rb#L50)   | YES |
| message | message accompanying alert | YES |
| start_date | when the alert is scheduled to begin appearing | NO |
| end_date | when the alert should stop appearing | NO |
 3. Sensu/Staff receives `201 Created` response with created Alert from `/api`
