### ISSUE TITLE
Create pre/post hooks in Jellyfish

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#128]
Here's the list of events that I see (there should be a BEFORE and an AFTER hook)

- [x] User login
- [x] User logout
- [x] Create project
- [ ] Archive project
- [x] Edit project
- [x] Delete project
- [x] Project approval
- [x] Project rejection
- [x] User creation
- [x] User deletion
- [x] User added to project 
- [ ] User removed from project
- [ ] OK Alert created
- [ ] WARNING Alert created
- [ ] CRITICAL Alert created
- [ ] Alert transition (going from one status to another)
- [ ] Add to Cart
- [ ] Remove from Cart
- [ ] Provision
- [x] Add product
- [ ] Edit product
- [ ] Make product active
- [ ] Make product inactive

**Comment by mafernando** [comment]
Looked at a couple different approaches to addressing this issue today.

Current approach is to break down this task into two subtasks:
1) Create a pre/post hook system which could/should tie into the module system being worked on by Thoughtbot
2) Implement a notification system using delayed jobs to avoid holding up the event in question by waiting for the notification to resolve

Am avoiding using pre/post commit hooks defined on models because that would cause the hooks to be invoked whenever we manipulate objects which may not always be desirable. One example would when manipulating objects from within the console.

**Comment by chriskacerguis** [comment]
@mafernando what events are we going to provide hooks for?

**Comment by mafernando** [comment]
@chriskacerguis, I'm working off the list you provided initially and adding onto them as use cases come to mind. I've removed the hooks gem as it looks like that we can get what we want just using plain old ruby class methods. Am working out the details between how the inter-play between the hooks and notification system should look like. 

Here is the current list I'm coding against:

Admin = Admin Only
User = Admin AND User

List of events (work in progress):
- [ ] User: Created new project
- [ ] Admin: Need to approve project
- [ ] User: Project Approved / Rejected
- [ ] User: New Alert
- [ ] User: Alert over
- [ ] User: Service X provisioned
- [ ] User: Checkout Summary

Examples of different notification types:
- Email (Text or HTML)
- SMS 
- Push
- Slack
- Custom

**Comment by chriskacerguis** [comment]
So, here's the list of events that I see (there should be a BEFORE and an AFTER hook)

- [ ] Create project
- [ ] Archive project
- [ ] Edit project
- [ ] Delete project
- [ ] Project approval
- [ ] Project rejection
- [ ] User creation
- [ ] User deletion
- [ ] User added to project 
- [ ] User removed from project
- [ ] OK Alert created
- [ ] WARNING Alert created
- [ ] CRITICAL Alert created
- [ ] Alert transition (going from one status to another)
- [ ] Add to Cart
- [ ] Remove from Cart
- [ ] Provision
- [ ] Add product
- [ ] Edit product
- [ ] Make product active
- [ ] Make product inactive

**Comment by mafernando** [comment]
Added https://github.com/projectjellyfish/api/tree/feature/add-hooks-to-controllers-with-notifications branch to address this issue.

**Comment by mafernando** [comment]
Am going through and verifying that each of these can be triggered from the hooks in their respective controller without issue:

- [x] User login
- [x] User logout
- [x] Create project
- ~~Archive project~~ ~ _removing until provision is setup_
- [x] Edit project
- [ ] Delete project
- [ ] Project approval
- [ ] Project rejection
- [ ] User creation
- [ ] User deletion
- [ ] User added to project 
- [ ] User removed from project
- [ ] OK Alert created
- [ ] WARNING Alert created
- [ ] CRITICAL Alert created
- [ ] Alert transition (going from one status to another)
- [ ] Add to Cart
- [ ] Remove from Cart
- [ ] Provision
- [ ] Add product
- [ ] Edit product
- [ ] Make product active
- [ ] Make product inactive

Since project/order_item creation require underlying data to verify, I am using a simple rake task to populate the DB with test data since our ```rake sample:demo``` task is no longer compatible with the current schema.

```
  desc 'Generates test data'
  task test: :environment do
    Staff.create!([
        { id: 4, first_name: 'Unused', last_name: 'Staff', email: 'unused@projectjellyfish.org', phone: nil, password: 'jellyfish', reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, role: 0, deleted_at: nil, secret: 'jellyfish-token'},
        { id: 2, first_name: 'ManageIQ', last_name: 'Staff', email: 'miq@projectjellyfish.org', phone: nil, password: 'jellyfish', reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 17, current_sign_in_at: '2015-02-06 17:04:10', last_sign_in_at: '2015-02-06 16:57:41', current_sign_in_ip: '54.172.90.47', last_sign_in_ip: '54.172.90.47', role: 1, deleted_at: nil, secret: 'jellyfish-token'},
        { id: 3, first_name: 'User', last_name: 'Staff', email: 'user@projectjellyfish.org', phone: nil, password: 'jellyfish', reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: '2015-02-13 18:00:54', last_sign_in_at: '2015-02-12 19:37:15', current_sign_in_ip: '128.229.4.2', last_sign_in_ip: '128.229.4.2', role: 0, deleted_at: nil, secret: 'jellyfish-token'},
        { id: 5, first_name: 'All', last_name: 'Users', email: 'projectjellyfish@bah.com', phone: nil, password: 'jellyfish', reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, role: 0, deleted_at: nil, secret: 'jellyfish-token'},
        { id: 1, first_name: 'Admin', last_name: 'Staff', email: 'admin@projectjellyfish.org', phone: nil, password: 'jellyfish', reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 36, current_sign_in_at: '2015-02-18 00:39:32', last_sign_in_at: '2015-02-17 20:28:51', current_sign_in_ip: '127.0.0.1', last_sign_in_ip: '108.45.125.67', role: 1, deleted_at: nil, secret: 'jellyfish-token'}
    ])
    Staff.connection.execute("ALTER SEQUENCE staff_id_seq RESTART #{Staff.all.order('id DESC').first.id + 1}")

    ProjectQuestion.create!([
        { id: 1, question: 'Project Description', help_text: '', required: true, deleted_at: nil, load_order: nil, options: [], field_type: 2},
        { id: 2, question: 'Project Charge Code', help_text: '', required: true, deleted_at: nil, load_order: nil, options: [], field_type: 2},
        { id: 3, question: 'Maintenance Day', help_text: '', required: true, deleted_at: nil, load_order: nil, options: [], field_type: 3},
        { id: 4, question: 'Performed Maintenance', help_text: '', required: true, deleted_at: nil, load_order: nil, options: [], field_type: 0},
        { id: 5, question: 'Default provisioning location', help_text: '', required: true, deleted_at: nil, load_order: nil, options: ['East Coast Data Center', 'West Coast Data Center', 'Classified Data Center'], field_type: 1},
        { id: 6, question: 'Will this run in production?', help_text: '', required: true, deleted_at: nil, load_order: nil, options: ['Yes', 'No'], field_type: 1},
        { id: 7, question: 'FISMA Classification', help_text: '', required: true, deleted_at: nil, load_order: nil, options: ['Low', 'Medium', 'High'], field_type: 1},
        { id: 8, question: 'Period of Performance', help_text: 'in months', required: nil, deleted_at: nil, load_order: 1, options: nil, field_type: 2}
    ])
    ProjectQuestion.connection.execute("ALTER SEQUENCE project_questions_id_seq RESTART #{ProjectQuestion.all.order('id DESC').first.id + 1}")

    Cloud.create!([
        { id: 1, name: 'AWS', description: nil, extra: '{}', deleted_at: nil},
        { id: 2, name: 'Azure', description: nil, extra: '{}', deleted_at: nil},
        { id: 3, name: 'Rackspace', description: nil, extra: '{}', deleted_at: nil},
        { id: 4, name: 'VMware', description: nil, extra: nil, deleted_at: nil},
        { id: 5, name: 'Google', description: nil, extra: nil, deleted_at: nil},
        { id: 6, name: 'Other', description: nil, extra: nil, deleted_at: nil},
        { id: 7, name: 'OpenStack', description: nil, extra: nil, deleted_at: nil}
    ])
    Cloud.connection.execute("ALTER SEQUENCE clouds_id_seq RESTART #{Cloud.all.order('id DESC').first.id + 1}")

    ProductType.create!([
        { id: 1, name: 'Infrastructure', description: 'Available Infrastructure'},
        { id: 5, name: 'Platforms', description: 'Available Platforms\n'},
        { id: 3, name: 'Databases', description: 'Available Database'},
        { id: 2, name: 'Big Data', description: 'Available Big Data Solutions'},
        { id: 6, name: 'Applications', description: 'Available Applications'},
        { id: 4, name: 'Storage', description: 'Available Storage'},
        { id: 7, name: 'Staff', description: 'Available Staff'}
    ])
    ProductType.connection.execute("ALTER SEQUENCE product_types_id_seq RESTART #{ProductType.all.order('id DESC').first.id + 1}")

    ManageIqProduct.create!([
        { id: 1, service_type_id: 8, service_catalog_id: 1, cloud_id: 1, chef_role: '--CHEF-ROLE--', options: {}}
    ])
    ManageIqProduct.connection.execute("ALTER SEQUENCE product_types_id_seq RESTART #{ManageIqProduct.all.order('id DESC').first.id + 1}")

    Product.create!([
        { id: 1, name: 'Small', description: 'Small EC2 Instance', active: true, img: 'products/aws_ec2.png', deleted_at: nil, product_type_id: 1, setup_price: '1.99', hourly_price: '0.001', monthly_price: '0.05', provisionable_id: 8, provisionable_type: 'manage_iq_product'},
    ])
    Product.connection.execute("ALTER SEQUENCE products_id_seq RESTART #{Product.all.order('id DESC').first.id + 1}")
  end
```

**Comment by stackus** [comment]
Shouldn't populate the database with data in the `id` column. For the code shown above, most of it does not relate to anything else so `id` can just be dropped and the additional `execute` statements are no longer needed.

The items that do you should use `Thing.find(n).related_thing.create!` to create one or more related objects.

**Comment by mafernando** [comment]
@stackus - thanks for the feedback. I won't commit these changes to the seed file, that's a separate ticket. I'm just using this as a crutch to verify that these hooks are getting fired on some kind of dummy data.

Will use incorporate ```.find(n)``` going forward.
