### ISSUE TITLE
Add Docker ProductType

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#133]
Need to add "Docker" (PaaS) as a productType.  Things we need to capture:

- RepoURL

**Comment by OBCENEIKON** [comment]
Adding to backlog for now until Monday when we discuss with Thoughtbot.

**Comment by masonforest** [comment]
I'd love to help out with the Docker stuff if possible! I'm not quite sure what this story means though. What happens when you provision a Docker ProductType? Does it spin up an EC2 instance with that Docker image running inside of it?

**Comment by chriskacerguis** [comment]
So, let me type up the work flow here
