### ISSUE TITLE
Refactor Alerts Controller and Associated Models

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#138]
Alerts needs to be refactored to support provision status and correct implementations of certain routes.  

- [x] Change order_id to order_item_id in Alert.rb
- ~~Change OrderItem.rb to add 'has many' relationship to Alerts~~ (still good idea to impl?)
- ~~Change Alert.rb to add 'has one' relationship to OrderItem~~ (still good idea to impl?)
- [x] Change Project.rb to add 'has many' relationship to Alerts
- [x] Change Alert.rb to add 'has one' relationship to Project
- [x] Change /alerts in AlertsController to pull only the most recent alert associated with a given Project/OrderItem
- [x] Correct logic for /alerts/sensu in AlertsController
- [x] Scope out load active alerts from Alerts Controller in Alerts.rb (pull only the most recent alert associated with a given Project/OrderItem)
- ~~Scope out load inactive alerts from Alerts Controller in Alerts.rb (pull only the most recent alert associated with a given Project/OrderItem)~~
- ~~Scope out load all alerts from Alerts Controller in Alerts.rb (pull only the most recent alert associated with a given Project/OrderItem)~~
- ~~Modify Alerts JSON response to align with UX coming from core~~ (aligned UX with core)
- ~~Figure out how to support system wide alerts since they will not be associated with a project.~~
- [x] Modify Alerts spec to test against aforementioned changes

**Comment by mafernando** [comment]
After discussing the issue with Stack, it looks the right course of action here is to add a polymorphic relationship on alerts against organizations, projects and order_item. 

Additionally, the issue of project alerts came up and demonstrated the need for an entity that could preserve messages but was unconcerned with time. Alerts are sequential by nature, so we could create a Message model and associate that with project to store any project-wide notifications but not require creating them against a service with id equal to zero.

**Comment by chriskacerguis** [comment]
@mafernando what's the word on this?

**Comment by mafernando** [comment]
@chriskacerguis - am working on this now.

**Comment by mafernando** [comment]
Context: Only order_items (and perhaps staff) should be allowed to have alerts. As they are currently implemented, there can only ever be one active alert associated with an entity. This is fine for services, but does not make sense for project-wide or (system) organization-wide alerts. An organization or project may want to broadcast several messages and have them all persist as active. Those messages may or may not have anything to do with the status of provisioned resources.

Proposition: Introduce a Message (final name TBD) model and allow organization and project to have many of them. A system-wide or project-wide message would be created instead of an alert. The status of a project can still be determined by examining the latest alerts attached to its services.

**Comment by mafernando** [comment]
My first pass of this can be found [here](https://github.com/projectjellyfish/api/tree/feature/refactor-tags-poly).

I wasn't sure how to setup the policy for polymorphic alerts, so am open to receiving feedback on how to implement that piece. 

Let me know what needs fixing!
