### ISSUE TITLE
Refactor poll_miq_vms to take into acount provisioned resources correctly

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#189]
Refactor poll_miq_vms to take into acount provisioned resources correctly
Also, fix upkeep poll_miq_vms to use touch instead of update_attributes.

**Comment by chriskacerguis** [comment]
@mafernando is this still valid?

**Comment by mafernando** [comment]
@chriskacerguis - I don't think this is valid anymore. Previously, this methods was pinging all the instances on MIQ regardless if they were provisioned by Jellyfish just to show we could collect instance status from MIQ. I think this job should be moved to the Jellyfish MIQ module. If we were to actively use it from the Jellyfish MIQ module, then we would need to modify it to only ping the instances from MIQ that we provisioned through Jellyfish. Thoughts?

**Comment by OBCENEIKON** [comment]
This has been moved over to the Jellyfish MIQ module, but I agree, it should only be concerned about instances that it provisioned. I'll start on that part now.
