### ISSUE TITLE
Need image_id option in Edit Products page for Amazon VM

### ISSUE THREAD

**Issue by jntullo** [projectjellyfish/api#191]
https://github.com/booz-allen-hamilton/jellyfish-ux/issues/151

**Comment by chriskacerguis** [comment]
This is just a ProductType setting that needs to be added.

**Comment by chriskacerguis** [comment]
Shouldn't have closed the API ticket (just the UX one)

**Comment by chriskacerguis** [comment]
No longer valid, this is an issue for the jellyfish manage iq module.
