### ISSUE TITLE
Restrict alerts to display only those where status is not OK

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#194]
Restrict alerts to display only those where status is not OK

**Comment by stackus** [comment]
The reason is you're making API work for a single client by doing that. Some client may expect that the `all_alerts` call will do just that, return all alerts. An open API such as this shouldn't assume what a client is going to want.

What should be done is the following.

- Make GET /alerts return an unfiltered list of alerts
- Add parameters to let a client choose to modify that list
    - Options such as active=true, status=[OK, CRITICAL,...], sort=[project, oldest]
- Create the logic to add the scopes requested by the client
- Remove the extra GET /alert_* actions
- Update UX to request the data it wants

**Comment by mafernando** [comment]
will be addressed in https://github.com/projectjellyfish/api/issues/138

**Comment by mafernando** [comment]
This issue has changed scope a bit given how alerts are now implemented. 

An entity (Project, Service, Organization, or Staff) can have multiple alert types associated with it.

![image](https://cloud.githubusercontent.com/assets/9356425/8479219/ea27da0c-209b-11e5-9050-2186668de700.png)

@stackus - do you think it makes sense to close this ticket?

**Comment by stackus** [comment]
I have to answer that with a question. Does the request to filter out OK alerts still stand?

**Comment by chriskacerguis** [comment]
@mafernando don't forget a service can have multiple current alerts

For example:

dbserver01
- CRITICAL: RAM usage at 90%
- CRITICAL: CPU usage at 99%

**Comment by mafernando** [comment]
@chriskacerguis: duly noted, which of the following entities do you only want display non-OK alerts for?
- projects (the project as a whole, e.g. audit is coming)
- services (for order items in a project)
- organization (proxy for system alerts)
- staff

**Comment by chriskacerguis** [comment]
all.

**Comment by stackus** [comment]
Should OK alerts never be recorded then?

**Comment by chriskacerguis** [comment]
No we need to see the transition to we can do reports on that

**Comment by mafernando** [comment]
The non-OK alert restriction would be applied to the entry points specified on Issue https://github.com/projectjellyfish/api/issues/790.

We will need to implement those first before being able to add the non-OK restriction to Projects, Services and Staff.

**Comment by mafernando** [comment]
this is now implemented for admin alerts (organizations).

the restriction has been noted on Issue https://github.com/projectjellyfish/api/issues/790 

this ticket is functionally a duplicate, so closing it.
