### ISSUE TITLE
Add support for Cloud Foundry

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#226]
Add support for Cloud Foundry

**Comment by calebthompson** [comment]
I'm confused - are these Fog issues to add functionality to https://github.com/fog/fog?

**Comment by chriskacerguis** [comment]
Yes

**Comment by calebthompson** [comment]
http://apidocs.cloudfoundry.org/200/

**Comment by calebthompson** [comment]
What specific features are we trying to support for cloudfoundry? It appears that it is more a competitor to Jellyfish than a thing we could leverage. http://pivotal.io/platform-as-a-service/pivotal-cloud-foundry

**Comment by chriskacerguis** [comment]
There's a lot to CloudFoundry for sure, but we are interested in it's PaaS parts (like OpenShift or Heroku).

So, from the marketplace it would be like the following:

User -> “I want to deploy my PaaS-ified app”

User -> [upload code]

Marketplace -> [parses application manifests in code]

Note: Perhaps we defined our own Schema for this, which can then "translate" into other PaaS schemas (Dockerfile, Heroku app.json, CloudFoundry manifest.yml, etc)

Marketplace -> “I see what you want to do in your code, here are your options with price and comparison"

1. Internal Docker
2. AWS Elastic Beanstalk
3. Heroku
4. CloudFoundry
5. OpenShift

Like the IaaS there are limitations to each.  For example, if I wanted to deploy a PHP app, then I can't deploy to CloudFoundry.

**Comment by mafernando** [comment]
Looking into using the [cloudfoundry-client](https://github.com/frodenas/cloudfoundry-client) to interface with CloudFoundry API

**Comment by mafernando** [comment]
I'm thinking that a gemified engine approach will enable us to incorporate provisioning capability through Cloud Foundry. 

Cloud Foundry deployment is similar to deployment via the Heroku toolbelt. The primary difference is that Heroku will create the underlying cloud (AWS) vm resource and then push git code onto it using the credentials you give it when you create an account. 

There is also an existing solution, [Pivotal Cloud Foundry](https://pivotal.io/platform-as-a-service/pivotal-cloud-foundry) which seems analogous to Heroku.

Open Topics:
- [ ] How to handle migrations ([delayed-jobs](https://github.com/collectiveidea/delayed_job) or [sidekiq](https://github.com/mperham/sidekiq) will require schema changes - how do we roll these back when modules are added/subtracted?)
- [ ] How to make REST calls to CloudFoundry 
- [ ] How to reference git repo
- [ ] How to specify Cloud backend

**Comment by mafernando** [comment]
Fun fact - the VM templates used by Cloud Foundry are called [stemcells](http://bosh.io/docs/understanding-bosh.html).

**Comment by mafernando** [comment]
Cloud Foundry maintains a set of [CLI tools](http://docs.cloudfoundry.org/devguide/installcf/install-go-cli.html) which allows you to manage your Cloud Foundry instance or resources similar to the Heroku toolbelt. Can be downloaded [here](https://github.com/cloudfoundry/cli/releases).

**Comment by chriskacerguis** [comment]
We can't use the cli tools. We need to stick with REST.

**Comment by mafernando** [comment]
@chriskacerguis - The CLI tools could be necessary if we go the OSS route of firing up our own Cloud Foundry Instance to use as the API endpoint vs using the commercially hosted one offered by [Pivotal Web Services](http://run.pivotal.io/). Not sure if we want to head the OSS route because it would require setting up a corresponding Cloud Foundry instance (controller) for each Jellyfish instance.

**Comment by chriskacerguis** [comment]
Not 100% sure that I'm following the use case here.  However, we can't rely on any CLI tools for as they may not be available.  So, CLI tools are out.
