### ISSUE TITLE
Refactor manage_iq_client

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#245]
- Running db:migrate will generate a few `Unable to annote manage_iq_client/...` lines in the log.
- These can be ignored, according to @stackus they are generated because the manage_iq_client is not backed by a database.
- We may want to revisit the client and complete its implementation. 
  - Currently only rake tasks are using it in its incomplete state, but that could change going forward.

For reference: https://github.com/ctran/annotate_models

**Comment by chriskacerguis** [comment]
@mafernando is this still a thing?  If not, can you please close?

**Comment by mafernando** [comment]
So as it turns out, there is a skip tag we can put on models that we want annotate to ignore. I discovered an issue with the way annotate checks for that tag, so I have proposed https://github.com/ctran/annotate_models/pull/243 to resolve the issue. Am awaiting on annotate to merge the PR.

**Comment by stackus** [comment]
This "client" isn't sacred and if it's not going to be used it can be deleted. If it ever needs to be resurrected, there's always the git history.

**Comment by mafernando** [comment]
Totally agree with you, just wanted to update the annotate gem while the issue was fresh on my mind. 

Maybe we add additional clients going forward and can tell annotate to skip them.

I also recognize that the `Annotate.load_tasks unless ENV.key? 'DISABLE_ANNOTATIONS'` check we put on [auto_annotate_models.rake](https://github.com/projectjellyfish/api/blob/master/lib/tasks/auto_annotate_models.rake#L33) should more or less prevent `rake db:migrate` from producing too much noise.

**Comment by mafernando** [comment]
Looks like my PR was merged into annotate. 

I'll throw a skip tag on the `manage_iq_client` and then we can close out this.

- [ ] Add skip tag to `manage_iq_client`

**Comment by chriskacerguis** [comment]
Taking care of this in https://github.com/projectjellyfish/api/issues/496

Closing.
