### ISSUE TITLE
Sample rake file was not encrypting authentication_token

### ISSUE THREAD

**Issue by OBCENEIKON** [projectjellyfish/api#254]

**Comment by stackus** [comment]
Also, the sample file should use `secret: '{token here}'` and not hardcode the pre-encrypted token.

**Comment by mafernando** [comment]
@stackus - where should the secret come from? randomly generated or set in .env beforehand?

**Comment by stackus** [comment]
@mafernando The sample uses `password: 'jellyfish'`, so `secret: 'jellyfish-token'` works. I meant encoded token, not pre-encoded token. (switched to tea today).

That said, I don't have an example of how the encrypted password or authentication token being in the sample could lead to a system hack. I do feel that putting encrypted strings into a repo is a bad thing™.
