### ISSUE TITLE
Allow users to be able to specify the value for a productType item.

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#269]
Create an entry in ProductTypes ("user_fillable") to allow for a user to add data when adding to cart.

**Comment by calebthompson** [comment]
Is there a separate issue for actually using this field, such that this issue is actually just adding a boolean flag to product_type in the database?

**Comment by brittballard** [comment]
Who is working on the UX portion of this story? This will require some pretty heavy collaboration I suspect.

**Comment by chriskacerguis** [comment]
It will be a combo of @AllenBW and @sonejah21

**Comment by brittballard** [comment]
I can start digging into some Angular if necessary. I just don't want to step on toes.

**Comment by sonejah21** [comment]
@chriskacerguis - should this title read "Allow users to be able to specify the value for a productType item"? 
@brittballard - pending Chris K's opinion and subsequent approval, i say you can dig in wherever you like. Angular help is always appreciated. If you start on this please let me know so I can change gears and assist.

**Comment by chriskacerguis** [comment]
fixed typo in title

**Comment by brittballard** [comment]
@sonejah21 I'm curious where you think this should happen? Should this happen when a person add a service to a project, or when they checkout?

**Comment by brittballard** [comment]
Once we complete this story, I don't know that we'll still need product types for anything beyond organization purposes. I think this will allow us to remove the product questions and answers stuff.

**Comment by brittballard** [comment]
I have changed my tune. We will still need product types.

**Comment by calebthompson** [comment]
This is going to become order_item.answers or similar. It's related to the product type changes I'm doing but I may handle it as a follow-up.

**Comment by calebthompson** [comment]
@chriskacerguis I need clarification on this. I'm of the opinion (and I've discussed it with @masonforest and @brittballard who agree) that all of the questions we just put onto Product in #466 should be moved to OrderItem. This means that we have fewer products and each one gets both sensible defaults and can be customized.

We'd also have questions that lived directly on products, such as AWS credentials which wouldn't vary by order but would differ by product.

This would mean expanding the current diagram:

```
  product_type
  ├── product
  │   └── Provisioning answers JSON column in database
  ├── Provisioning questions JSON object in memory
  │
  └── Rails.application.config.product_types configuration stores types
```

To include order items, where each set of questions and answers are completely distinct (not overrides, only answered in one place):

```
  product_type
  ├── product
  │   └── Provisioning answers like credentials
  ├── order item
  │   └── Specific answers like instance size or availability
  └── Rails.application.config.product_types configuration stores types
      ├── product questions
      └── order questions

```

**Comment by mafernando** [comment]
user specified values for a product types now are persisted as `product.provisioning_answers`. closing this issue.
