### ISSUE TITLE
'protect_from_forgery' should be called in ApplicationController

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#275]
A  vulnerability was found by Code Climate.

https://codeclimate.com/repos/54d4fa64695680762a0024c5/security/a88969674cc5a97cd65b06a0494358fb

**Comment by chriskacerguis** [comment]
Can you please investigate this?  I know that we been messing with that on and off.

**Comment by stackus** [comment]
API+UX is an odd duck. API+UX create a single site like experience but it's really an API with an HTML5 client.

**Comment by chriskacerguis** [comment]
I think your PR from a few minutes ago resolved this issue
