### ISSUE TITLE
Move timestamps to first columns in migrations

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#307]
Move the timestamps to the first columns in migrations

**Comment by calebthompson** [comment]
Check with @brittballard, but I don't think we'd want to modify old migrations, just make this a habit for new tables in the future.

**Comment by brittballard** [comment]
I would agree, it's probably best to just use this convention moving forward. Otherwise we run the risk that new people's schema.rb files differ from ours, which could get to be a pain.

**Comment by stackus** [comment]
Yeap, agree with both of the above.

That said, we have a mountain of migrations. We could delete them and add a migration with the current schema.rb contents. You could rearrange the existing schema to put the timestamps first then. Leave it for others to decide if this is a good idea.

**Comment by chriskacerguis** [comment]
ok, cool.  I'll close the ticket.
