### ISSUE TITLE
Update JSON column types to JSONB

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#311]
After we update to Rails 4.2 we need to change JSON columns to JSONB columns

Rails 4.2: https://github.com/projectjellyfish/api/issues/310

**Comment by calebthompson** [comment]
@OBCENEIKON Am I going to be stepping on your toes if I knock this out?

**Comment by calebthompson** [comment]
Resolved in 7c5922cf5d1d8b27aa2ee2414d5dda9c77d4a2c0
