### ISSUE TITLE
API needs to be versioned

### ISSUE THREAD

**Issue by brittballard** [projectjellyfish/api#314]
In order for the API to be used by clients other than our own internally maintained UX project it needs to be versioned.

**Comment by chriskacerguis** [comment]
IS this done?

**Comment by mafernando** [comment]
@calebthompson - I recall you mentioning that in the new API/UX URLs that we prepend /api/v1 to all the routes. Is this the versioning of the API that this issue refers to?

**Comment by calebthompson** [comment]
Yup, this is done.
