### ISSUE TITLE
Creating new Project gives a 422

### ISSUE THREAD

**Issue by OBCENEIKON** [projectjellyfish/api#321]
@gnklausner found that when trying to create a new project through the UX, the API gave him a 422. When looking at the JSON response, it's telling him that project_answers expects an array and is nil.

This could be an issue with the seed file, as I saw that there were no pre-created projects which would indicate no pre-created project questions or answers. But I also did not see an area to create project questions or answers.

It also looks like a lot of refactoring of this file has been done by @calebthompson, though I don't think this caused the issue.

**Comment by chriskacerguis** [comment]
So, this is a UX issue?

**Comment by calebthompson** [comment]
I'm a little unclear on how all the param stuff works. I believe that this code requires that a project_question_id be included for each project_answer array member, but that project_answers itself can be nil/empty:

```
      api.param :project_answers, Array, desc: 'Project answers' do
        api.param :project_question_id, :number, desc: 'Id for valid project question', require: true
      end

```

**Comment by OBCENEIKON** [comment]
Turns out, this looks like a UX issue. If there are no project questions, it's sending an empty array for project_answers, which strong parameters doesn't like. Instead, the UX should not send a project_answers array if there aren't any project questions.
