### ISSUE TITLE
Product_types is empty

### ISSUE THREAD

**Issue by gnklausner** [projectjellyfish/api#327]
product_types is empty, which I believe is the cause of not being able to add a product on the front-end.
![producttypesempty](https://cloud.githubusercontent.com/assets/9269960/6531370/d9cebc4e-c406-11e4-8b43-509e598cc10e.png)

**Comment by gnklausner** [comment]
Probably linked to #326

**Comment by chriskacerguis** [comment]
@calebthompson  Is this valid?

**Comment by calebthompson** [comment]
Nope. Dealt with.
