### ISSUE TITLE
Unable to add products

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#328]
I'm unable to add products via the UX.  Without the Product Types / Modules, I should be able to add products just with the following:

* Name
* Description
* Icon
* Active (Set Active or Not)
* Setup Price
* Hourly Price
* Monthly Price
* Product Type (with nothing in the system it would be "None") 

This may be a UX issue, if so, please create a ticket over there and reference this one.

**Comment by brittballard** [comment]
The button is disabled for me when I try to do this. I might be doing something wrong I'm honestly not sure.

**Comment by brittballard** [comment]
![uploads/a53646b2-8793-4ccc-9a3b-1d5778081713/create product.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa53646b2-8793-4ccc-9a3b-1d5778081713%2Fcreate+product.gif)

**Comment by brittballard** [comment]
![uploads/d036a35f-7b4f-4c8b-ad2b-0bf196047b0f/create product with console.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd036a35f-7b4f-4c8b-ad2b-0bf196047b0f%2Fcreate+product+with+console.gif)

**Comment by brittballard** [comment]
I have added a ticket in the UX repo as well for this.

**Comment by brittballard** [comment]
@stackus fixed the button issue. I'm now working on the route issue.

**Comment by brittballard** [comment]
https://github.com/projectjellyfish/ux/pull/277
https://github.com/projectjellyfish/api/pull/338
