### ISSUE TITLE
Move "internal login" system to be a module

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#329]
Move "internal login" system to be a module using pre/post hooks.

**Comment by OBCENEIKON** [comment]
After talking to @brittballard and @calebthompson, modularizing the login system would be a bad idea. 

Sticking with devise though, we could just create devise modules to be installed as gems. Hopefully most customers will be using a technology that already has a devise module written like LDAP, SSO or OAuth. But for other customers we may have to write a devise module implementing their authentication method.

**Comment by chriskacerguis** [comment]
Well, Devise is still module, it's just a different module.  Can you please start the process to get the internal system, and oauth to use Devise exclusively, then work on LDAP (https://github.com/projectjellyfish/api/issues/115)

**Comment by chriskacerguis** [comment]
So, let's make sure we are using Devise for everything, and then make some modules for it (and document how they work)
