### ISSUE TITLE
Add team_member_products controller

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#333]
Currently manage_iq and team_member are the two provisionable product types in API.

Since products have been decoupled from their manage_iq components we need to build out controllers for each different provisionable type (like in the case of manage_iq_products_controller). 

Todo: Add a controller for TeamMemberProducts.

**Comment by mafernando** [comment]
@OBCENEIKON - is this still relevant given that staff are added to projects via Groups/Memberships/Projects?

**Comment by OBCENEIKON** [comment]
@mafernando - I was wondering the same thing. I don't think it is.
@chriskacerguis - What do you think, is this still relevant?

**Comment by chriskacerguis** [comment]
@mafernando @OBCENEIKON Nope, not relevant.

**Comment by OBCENEIKON** [comment]
Closing this issue as it's no longer relevant.
