### ISSUE TITLE
Align UX and API on Product Create/Edit

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#335]
The Create/Update methods have been moved out of the ProductsController into the ManageIqProductsController.

UX is currently expecting Create/Update methods defined on Products Controller which is causing an 
```
AbstractController::ActionNotFound (The action 'create' could not be found for ProductsController):
```
error to be thrown.

Figure out a way to resolve this.

**Comment by chriskacerguis** [comment]
IS this the same issue here:

https://github.com/projectjellyfish/ux/issues/268

**Comment by mafernando** [comment]
Duplicate of [UX#268](https://github.com/projectjellyfish/ux/issues/268) closing.
