### ISSUE TITLE
Document how to build a module

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#350]
We need to create a document on how to build a module

**Comment by calebthompson** [comment]
I can document the process for adding products.

**Comment by mafernando** [comment]
See Issue https://github.com/projectjellyfish/api/issues/500 for the module documentation (work in progress).

**Comment by mafernando** [comment]
Documentation is now on the wiki:
- [module setup](https://github.com/projectjellyfish/api/wiki/Jellyfish-Module-Setup)
- [add module functionality](https://github.com/projectjellyfish/api/wiki/Add-Module-Functionality)
