### ISSUE TITLE
Serve ux angular app from Rails (combining repos)

### ISSUE THREAD

**Issue by calebthompson** [projectjellyfish/api#358]
- [x] Can't view Admin items
- [x] No background images
- [x] Can't fill in other than 0 on new project form

**Comment by brittballard** [comment]
Logged in as an admin I currently can't access any of the Admin menu items.

![screen shot 2015-03-25 at 9 43 47 am](https://cloud.githubusercontent.com/assets/129564/6827083/7b4daadc-d2d3-11e4-88f2-457fa3128757.png)

**Comment by brittballard** [comment]
This one is probably pretty simple to fix, but there are some issues with the css images.
![screen shot 2015-03-25 at 9 45 11 am](https://cloud.githubusercontent.com/assets/129564/6827128/b5fb8500-d2d3-11e4-9b9a-3ff93a7d7e92.png)
![screen shot 2015-03-25 at 9 45 06 am](https://cloud.githubusercontent.com/assets/129564/6827127/b5fad52e-d2d3-11e4-84c8-3f99aa669023.png)
![screen shot 2015-03-25 at 9 45 01 am](https://cloud.githubusercontent.com/assets/129564/6827126/b5fadb00-d2d3-11e4-9e61-39027188f69d.png)
![screen shot 2015-03-25 at 9 44 47 am](https://cloud.githubusercontent.com/assets/129564/6827125/b5f8725c-d2d3-11e4-8dd2-539b72d90c20.png)

**Comment by cluobah** [comment]
I can only type zeroes into the budget box? Ignore me if this is desired demo behavior...
![createprojbudget](https://cloud.githubusercontent.com/assets/10980636/6827160/45a0ee68-d2dc-11e4-82e9-d97fc55434c2.PNG)

**Comment by calebthompson** [comment]
@cluobah Super weird. I can't think of anything I would have changed there, but it definitely doesn't work on the merged stuff and did before.

**Comment by cluobah** [comment]
@calebthompson Are all these attributes of the form right? 
![budgetelement](https://cloud.githubusercontent.com/assets/10980636/6829540/726dbbca-d2ea-11e4-97c7-bfa5cb95d823.PNG)

**Comment by calebthompson** [comment]
Yeah they're the same on https://jellyfish-ux-dev.herokuapp.com/project/new.
