### ISSUE TITLE
Add ability to add "admin" settings via Module

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#359]
Add ability to add "admin" settings via a Module

**Comment by jntullo** [comment]
thoughts on adding this functionality to each individual module? ie the jellyfish-azure module adds the functionality to add the azure admin settings

**Comment by chriskacerguis** [comment]
I think that's a good way to do it.  @mafernando thoughts?

**Comment by mafernando** [comment]
@chriskacerguis - i think the approach of using environment variables for those admin settings would be ideal. That way they could be added through an initializer. 

Adding them as they are could be difficult if the module didn't have visibility into the admin_settings schema. We could make an admin settings module to get around this issue and then add it to jellyfish-azure or any other module, but that may be more work than we want to do.

**Comment by jntullo** [comment]
@mafernando I agree with the environment variables.

Perhaps disable certain admin settings if that gem / module is not installed?

**Comment by chriskacerguis** [comment]
No longer valid

**Comment by mafernando** [comment]
@chriskacerguis - do we want to make a call out in the our gem building guide to have environment variables loaded using a dotenv file?

**Comment by chriskacerguis** [comment]
I would say call it out to use environment settings, dotenv just makes it easier to set on our Mac (dev environment).
