### ISSUE TITLE
Return mobile_token on successful sign in

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#361]
Requirements:
- [x] Return mobile_token on successful sign in
- [x] Email Chris upon completion

**Comment by mafernando** [comment]
Reopening per problem direction from @chriskacerguis

**Comment by mafernando** [comment]
@chriskacerguis - we need to have API check against a user's encrypted token when they attempt to auth with token vs using the hard coded token value currently in place.

**Comment by chriskacerguis** [comment]
Ok

**Comment by jklarfeld** [comment]
Additionally it does not seem that a new token can be requested at any time.  A POST to the /staff/sign_in results in a token the first time, but a second POST is a 500 error.

I also cannot find any method of obtaining a new token using only the existing token (this would be massively helpful to prevent having to store a password on the device).

**Comment by mafernando** [comment]
@jklarfeld - you should now be able to login to API with 
```
POST /api/v1/staff/sign_in.json HTTP/1.1
Content-Type: application/json
Host: localhost:3000
Connection: close
User-Agent: Paw/2.1.1 (Macintosh; OS X/10.9.5) GCDHTTPRequest
Content-Length: 71

{"staff":{"email":"email","password":"password"}}
```

and get back the following json

```
{
  "id": 1,
  "first_name": "first",
  "last_name": "last",
  "email": "email",
  "phone": null,
  "role": "role",
  "created_at": "2015-03-27T01:21:50.791Z",
  "updated_at": "2015-03-27T01:25:30.818Z",
  "api_token": "api_token"
}
```

subsequent API requests would then provide the user email and api_token from sign in

```
GET /api/v1/products HTTP/1.1
X-Staff-Token: api_token
X-Staff-Email: email
Content-Type: application/x-www-form-urlencoded
Host: localhost:3000
Connection: close
User-Agent: Paw/2.1.1 (Macintosh; OS X/10.9.5) GCDHTTPRequest

```

Let me know if you encounter any issues here.

**Comment by mafernando** [comment]
Thanks to @calebthompson for helping me work through this one. 

Based on our conversation, we could use the [devise token auth gem](https://github.com/lynndylanhurley/devise_token_auth) to add more functionality to api token auth. And we have some great [devise token auth information](https://github.com/plataformatec/devise/wiki/How-To:-Simple-Token-Authentication-Example) we can refer to for this.

Also, based on this [interesting example](https://github.com/thoughtbot/clearance/blob/aefdc076fe92ed5168bbc1984dec66f8475d0654/lib/clearance/password_strategies/bcrypt.rb#L10), it seems that we should be able to compare a BCrypt Password obj with a string. We should probably investigate why the [token?](https://github.com/projectjellyfish/api/blob/master/app/models/concerns/token_authenticable.rb#L14) method defined on the TokenAuthenticable concern module is not behaving as expected.

**Comment by mafernando** [comment]
Created PR [#440](Activates TokenAuthentication on token api #440) to incorporate Stack's feedback on PR [#439](https://github.com/projectjellyfish/api/pull/439). Activates TokenAuthentication on api_token returned on JSON response.
