### ISSUE TITLE
Build Cron Job for Modules

### ISSUE THREAD

**Issue by OBCENEIKON** [projectjellyfish/api#363]
Create a way for modules to run cron jobs using the whenever gem.

**Comment by OBCENEIKON** [comment]
@chriskacerguis The only thing I am finding related to the rufus-scheduler process stopping is when the ruby server is stopped. It appears thats the only way the process can be stopped, so jobs will stop running when the application stops running.

**Comment by chriskacerguis** [comment]
Let's run with rufus.  Please create a process to check to make sure it is running, if it hasn't run in 5 minutes, please create an alert.
