### ISSUE TITLE
Need UI for viewing all servers

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#380]
<a href="https://github.com/chriskacerguis"><img src="https://avatars.githubusercontent.com/u/2414647?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chriskacerguis](https://github.com/chriskacerguis)**
_Thursday Jan 22, 2015 at 15:44 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/110_

----

Need a UI for viewing all servers

Core: https://github.com/booz-allen-hamilton/jellyfish-core/issues/116

**Comment by AllenBW** [comment]
duplicate of #477 CLOSED TO PRESERVED SANITY.
