### ISSUE TITLE
Need UX for admin to create alerts

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#381]
<a href="https://github.com/chriskacerguis"><img src="https://avatars.githubusercontent.com/u/2414647?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chriskacerguis](https://github.com/chriskacerguis)**
_Monday Jan 26, 2015 at 19:52 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/118_

----

We need a UX for an admin to be able to create alerts (or announcements).  Put this under the admin tab.

- [x] List Admin created alerts
- [x] Delete Admin created alerts
- [x] Edit an Admin created alert
- [x] Create a new Admin alert

**Comment by chriskacerguis** [comment]
<a href="https://github.com/sonejah21"><img src="https://avatars.githubusercontent.com/u/5269893?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sonejah21](https://github.com/sonejah21)**
_Tuesday Mar 17, 2015 at 18:50 GMT_

----

The UX game plan: 
![uploads/d9941f99-9533-4683-8575-2a0f0b1b7600/alerts_admin_navbar_option1.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd9941f99-9533-4683-8575-2a0f0b1b7600%2Falerts_admin_navbar_option1.png)

![uploads/8f0eec4f-3b69-4093-8f90-39aab4f86e38/alerts_admin_sidebar_option1.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8f0eec4f-3b69-4093-8f90-39aab4f86e38%2Falerts_admin_sidebar_option1.png)

**Comment by chriskacerguis** [comment]
<a href="https://github.com/gnklausner"><img src="https://avatars.githubusercontent.com/u/9269960?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gnklausner](https://github.com/gnklausner)**
_Friday Mar 20, 2015 at 23:02 GMT_

----

Added the ability to undo the deletion of an alert while the user is still on the page. 
Adjusted the "Actions" column to be more user friendly. 
Serious thanks to @sonejah21 for figuring out how to style the deleted row!

**Table before deletion**
![alertstablebeforedelete](https://cloud.githubusercontent.com/assets/9269960/6762259/30a4d6d4-cf33-11e4-91e9-e3326f2517ba.png)

**Table after deletion**
![alertstableafterdelete](https://cloud.githubusercontent.com/assets/9269960/6762261/39c33e22-cf33-11e4-8411-7dc3d6f6e648.png)


Remaining Tasks:
-Add flashes for creation of alert, update of alert, and undo of delete
-Remove delete button from the update form
-Add help text for field validation in creation/update form

**Comment by chriskacerguis** [comment]
<a href="https://github.com/gnklausner"><img src="https://avatars.githubusercontent.com/u/9269960?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gnklausner](https://github.com/gnklausner)**
_Monday Mar 23, 2015 at 16:08 GMT_

----

-Added flashes
-Removed delete button from update from
-Fixed bug with clicking edit/delete after clicking undo

TODO:
-Add help text for field validation in creation/update form

**Comment by chriskacerguis** [comment]
<a href="https://github.com/sonejah21"><img src="https://avatars.githubusercontent.com/u/5269893?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sonejah21](https://github.com/sonejah21)**
_Monday Mar 23, 2015 at 20:00 GMT_

----

Changes per Chris K's quick review.

On Main Alerts screen:
- [x]  Actions "[icon] edit" and "[icon] delete" should move back to the right side of the screen (like the other screens). We can address changing this design long term, but for now we want to maintain consistency.
- [x] Remove time from "Start Date" and "End Date" columns.
- [ ]  Create two new columns: "Start Time" and "End Time".  The times can be formatted as such: "12:00AM CST" or "3:39PM CST". Main changes are removing the seconds and adding the time zone. 
- [x]  The Status column will contain color-coded icons instead of text when showing up in this list. The Status column will be on the far left side. The icon should be centered in the column. It should contain a tooltip/hover that states the text version of the status. See ticket #283.

On ADD Alerts & EDIT Alerts screens:
- [x]  Remove "Unknown" status and "Pending" status. These are system statuses and cannot be selected.
- [x] Add the appropriate Status icon to each selection in the dropdown list. it will look like this: "[warning icon] WARNING", or be similar to the styling of the edit and delete (with icon + word).
- [x]  Should say "Back to Alerts" instead of "Back to Admin Alerts".
- [ ]  Add form fields for "Start Time" and "End Time". It should be hours and minutes, with a time zone option.
- [x]  Make "Message" field in ADD ALERT a textarea, not an input field.

**Comment by chriskacerguis** [comment]
<a href="https://github.com/gnklausner"><img src="https://avatars.githubusercontent.com/u/9269960?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gnklausner](https://github.com/gnklausner)**
_Monday Mar 23, 2015 at 21:42 GMT_

----

* For the Actions "edit" and "delete", can I create a new ticket and adjust it for project questions to be consistent with our page? I believe that is the only place that shows up. LoE: ~20min
* The time-zones will have to be thought out a bit more. I know we can create a mapping of "Some-Time-Zone-String" -> UTC Timezone Offset, but how we want to accomplish doesn't appear obvious to me. (For reference: http://stackoverflow.com/questions/952466/where-can-i-find-a-list-of-timezones-in-tabular-format ). [Moment.js](http://momentjs.com/timezone/docs/) seems like it may be useful for this.

**Comment by gnklausner** [comment]
It appears you cannot go from timezone offset to a string representation of a timezone, as the mapping is one to many. Newer browsers make the abbreviation available, but this is not guaranteed to be implemented or in a standardized format (IE uses "EDT" while Mozilla uses "(EDT)"). Options:
* There is a library for guessing the timezone, but it is not guaranteed to be correct 100% of the time: [jsTimeZoneDetect](http://pellepim.bitbucket.org/jstz/). 
* Wing it by parsing Date.toLocaleString
* Use the offset instead of an abbrevation (e.g. "UTC -240")
* A statement that says "All times are in local time"
* Ultimately, the best option may be to have a setting for a user to choose a timezone from a list of strings, which will set something like:
    * user.timezone.name (America/New_York)
    * user.timezone.abbr (EST)
    * user.timezone.utcOffset (-240)

For more, see this [stackOverflow](http://stackoverflow.com/questions/28374901/get-timezone-abbreviation-using-offset-value)

**Comment by chriskacerguis** [comment]
Okay, then just show the offset.

**Comment by klausner-garrett** [comment]
@chriskacerguis , @sonejah21 : :+1: || :-1: ?
![image](https://cloud.githubusercontent.com/assets/10980394/7049058/b55e4ae4-dde4-11e4-994c-fcaeb965873f.png)

**Comment by chriskacerguis** [comment]
:+1:
