### ISSUE TITLE
Need UX for internal CMS system

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#387]
**Remaining Tasks:**
- [x] Adding content pages does not automatically update the Pages sidebar set, need to fix this
- [ ] Add Admin View for Page revisions (to allow revert and diff) 
  - I propose that this moves into its own issue
- [x] Need to add icon for Pages sidebar item

_OLD STUFF BELOW_

We will need to build out a system for users to store basic pages.

- [x] Users: view
- [x] Admin: List all pages
- [x] Admin: Edit page
- [x] Admin: New page
- [x] Admin: Delete page
- ~~Admin: View Page revisions (to allow revert and diff)~~ - _see below_

Initial release, just support markdown for formatting.

**Comment by mafernando** [comment]
Started to poke around on this one and am looking into the options specified [here](https://hackhands.com/9-best-ruby-rails-content-management-systems-cms).

**Comment by mafernando** [comment]
**Current approach:**
- reuse existing content pages rails controller, model and policy
- update those components to align against the current roles/memberships/groups (if necessary)
- add [angular-markdown-directive](https://github.com/btford/angular-markdown-directive) to render static pages from db
- add [angular-markdown-editor](https://github.com/JimLiu/angular-markdown-editor) to edit static pages with

**Comment by mafernando** [comment]
Current working branch is [here](https://github.com/projectjellyfish/api/tree/feature/ux-for-cms).

Remaining Tasks:
- [ ] Add Admin View for Page revisions (to allow revert and diff)
- [ ] Adding content pages does not automatically update the Pages sidebar set, need to fix this

**Comment by stackus** [comment]
@sonejah21 Could you create a pair of sidebar icons for 'Pages'?

**Comment by sonejah21** [comment]
Sent the pair of Pages icons out yesterday via Slack, but am including them here too, just for reference. I can edit them if folks want them to change.
![ic_sidenav_pages_normal](https://cloud.githubusercontent.com/assets/5269893/9138470/170efeac-3cf2-11e5-8754-2fc05295dde0.png)
![ic_sidenav_pages_selected](https://cloud.githubusercontent.com/assets/5269893/9138471/1712366c-3cf2-11e5-9f27-1dbb205bdcd1.png)
