### ISSUE TITLE
Need to display a MOTD on login page

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#388]
<a href="https://github.com/chriskacerguis"><img src="https://avatars.githubusercontent.com/u/2414647?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chriskacerguis](https://github.com/chriskacerguis)**
_Wednesday Jan 28, 2015 at 19:57 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/130_

----

Display the MotD on the login page

**Comment by chriskacerguis** [comment]
<a href="https://github.com/sonejah21"><img src="https://avatars.githubusercontent.com/u/5269893?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sonejah21](https://github.com/sonejah21)**
_Friday Mar 13, 2015 at 14:56 GMT_

----

(MotD = Message of the Day, right?) May I have an example of a login page MotD?

**Comment by chriskacerguis** [comment]
<a href="https://github.com/chriskacerguis"><img src="https://avatars.githubusercontent.com/u/2414647?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chriskacerguis](https://github.com/chriskacerguis)**
_Friday Mar 13, 2015 at 17:19 GMT_

----

Here's an example

![page_login_motd](https://cloud.githubusercontent.com/assets/2414647/6643555/2a12d432-c97b-11e4-937b-870a9321cbb4.gif)

**Comment by AllenBW** [comment]
since you decided to assign me to this issue... we talking about something the admin updates? if so i would like to request that some deliver onto us an endpoint for bashing

**Comment by AllenBW** [comment]
Satisfied by pr #803
