### ISSUE TITLE
Enhance /dashboard to be more dashboard-like

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#393]
We need to make /dashboard more dashboard-like.

- [x] Move current content of /dashboard to /projects (a project list page)
- [ ] How many of each product type (for all) am I running (sum of projects)
- [ ] How much budget do I have

**Comment by chriskacerguis** [comment]
<a href="https://github.com/chriskacerguis"><img src="https://avatars.githubusercontent.com/u/2414647?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chriskacerguis](https://github.com/chriskacerguis)**
_Thursday Feb 12, 2015 at 20:04 GMT_

----

We'll need to wireframe this and get with Jarid for his input.  Lots to discuss here.

**Comment by AllenBW** [comment]
Views planned for initial release:

    Service Diversity Overview, overall service counts and service counts by project
    Budget Analysis, overall spent, overall allocated, and by each project

Views envisioned:

    Order Insight, history and costs over time, breakdown cost for each
    Service Usage Analysis, in depth statistics on different services
    Financial Projections, burn rates, etc
    User Utilization, statistics about users usage
    Maintenance Day Statistics, that.
    Others

**Comment by AllenBW** [comment]
old old old
