### ISSUE TITLE
UX for archiving projects

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#394]
We need a UX for archiving projects.

FYI - Don't allow projects with Active services to be archived.

**Comment by chriskacerguis** [comment]
<a href="https://github.com/chriskacerguis"><img src="https://avatars.githubusercontent.com/u/2414647?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chriskacerguis](https://github.com/chriskacerguis)**
_Saturday Feb 07, 2015 at 03:29 GMT_

----

Don't allow projects with Active services to be archived.

**Comment by chriskacerguis** [comment]
<a href="https://github.com/sonejah21"><img src="https://avatars.githubusercontent.com/u/5269893?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sonejah21](https://github.com/sonejah21)**
_Thursday Mar 12, 2015 at 14:33 GMT_

----

Will need more info on this ticket and what is needed to create the UX.

**Comment by AllenBW** [comment]
Recent activity means it's higher priority?

**Comment by AllenBW** [comment]
holding off on this until #855

**Comment by sonejah21** [comment]
See JEL-17: https://boozallen.atlassian.net/browse/JEL-17
