### ISSUE TITLE
Add Manage IQ Enabled checkbox on settings page

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#400]
<a href="https://github.com/jntullo"><img src="https://avatars.githubusercontent.com/u/2433314?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jntullo](https://github.com/jntullo)**
_Tuesday Feb 17, 2015 at 15:47 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/175_

----

Need checkbox to determine whether MIQ is enabled or disabled. Should be false by default.

**Comment by mafernando** [comment]
this is done via dotenv var setting. closing.
