### ISSUE TITLE
Add Azure settings tab to Settings page

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#401]
<a href="https://github.com/jntullo"><img src="https://avatars.githubusercontent.com/u/2433314?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jntullo](https://github.com/jntullo)**
_Wednesday Feb 18, 2015 at 15:17 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/183_

----

Needed inputs are:
- Azure pem 
- Azure sub id
- Azure api url

**Comment by mafernando** [comment]
these are moved to the jellyfish-fog gem. closing.
