### ISSUE TITLE
Refactor gulpfile.js from a D on Code Climate

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#417]
<a href="https://github.com/chriskacerguis"><img src="https://avatars.githubusercontent.com/u/2414647?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chriskacerguis](https://github.com/chriskacerguis)**
_Tuesday Mar 03, 2015 at 18:31 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/247_

----

https://codeclimate.com/repos/54d4fa726956803255002db9/gulpfile.js

**Comment by calebthompson** [comment]
No longer necessary - this has been removed.
