### ISSUE TITLE
Change Project Reject To Delete From Post

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#419]
<a href="https://github.com/mafernando"><img src="https://avatars.githubusercontent.com/u/9356425?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mafernando](https://github.com/mafernando)**
_Monday Mar 09, 2015 at 20:00 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/270_

----

Project Reject is currently using a Post from the UX side
https://github.com/projectjellyfish/ux/blob/master/assets/js/app/projects/projects_resource.js#L31
But Project Reject expects a Delete from the API side
https://github.com/projectjellyfish/api/blob/master/config/routes.rb#L89
Need to change UX to align with expected behavior from API, so make UX use DELETE instead of POST

**Comment by tangerine007** [comment]
Rejection of Project only occurs on refresh.
![image](https://cloud.githubusercontent.com/assets/4211939/7094637/15f2fe9c-df91-11e4-96b3-e7288763e56d.png)
Pressing the reject button rejects the project, but nothing happens until you revisit the page.

**Comment by mafernando** [comment]
nonissue after api/ux merge. closing.
