### ISSUE TITLE
Ensure site is ADA compliant/ Section 508 Compliance

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#420]
<a href="https://github.com/chriskacerguis"><img src="https://avatars.githubusercontent.com/u/2414647?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chriskacerguis](https://github.com/chriskacerguis)**
_Monday Mar 09, 2015 at 20:22 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/271_

----

**Comment by chriskacerguis** [comment]
<a href="https://github.com/stackus"><img src="https://avatars.githubusercontent.com/u/158579?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [stackus](https://github.com/stackus)**
_Monday Mar 09, 2015 at 20:29 GMT_

----

Accessibility in Angular Guide : https://docs.angularjs.org/guide/accessibility

**Comment by AllenBW** [comment]
http://inbound.anchorstl.com/ada-compliance-and-your-website-are-you-compliant/

a few plugins for fun, preliminary glance has me thinking where we'll be lacking is our adherence to a heading structure

**Comment by sonejah21** [comment]
I plugged in the ng-Aria gem and will finish this ticket once we have the new "john papa" style of Angular plugged in. I'll be using this checklist and other sites to drive the implementation: http://www.w3.org/WAI/eval/preliminary#headings

**Comment by AllenBW** [comment]
thumbs up yeah!

**Comment by sonejah21** [comment]
This will take place as soon as Allen has finished the

**Comment by chriskacerguis** [comment]
moved feature to Trello
