### ISSUE TITLE
Create /admin landing page

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#421]
Stack and I chatted, and we have decided that having an Admin landing page might be a good idea. We've already moved the list of Projects out of the sidebar in the ux-refresh, and onto its own My Projects landing page, and we'd like to remain consistent.

**Comment by chriskacerguis** [comment]
<a href="https://github.com/chriskacerguis"><img src="https://avatars.githubusercontent.com/u/2414647?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chriskacerguis](https://github.com/chriskacerguis)**
_Wednesday Mar 11, 2015 at 18:16 GMT_

----

ok

**Comment by sonejah21** [comment]
See JEL-18: https://boozallen.atlassian.net/browse/JEL-18
