### ISSUE TITLE
Center the status "bell" icon in Project Alerts grid of project/:id

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#422]
<a href="https://github.com/sonejah21"><img src="https://avatars.githubusercontent.com/u/5269893?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sonejah21](https://github.com/sonejah21)**
_Friday Mar 13, 2015 at 15:18 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/282_

----

![uploads/50383ec2-8274-453d-8e76-91999cc8ed28/Screen Shot 2015-03-13 at 10.58.51 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F50383ec2-8274-453d-8e76-91999cc8ed28%2FScreen+Shot+2015-03-13+at+10.58.51+AM.png)

**Comment by sonejah21** [comment]
Ben Hahn @tangerine007 has taken this ticket to work on. He doesn't have access to assign himself to it, so I am making note of it here.

**Comment by tangerine007** [comment]
![422-bell](https://cloud.githubusercontent.com/assets/4211939/6946181/9587b214-d86c-11e4-9b40-f11fbebfac9a.png)
