### ISSUE TITLE
Status column contents are missing in Project Orders grid on /project/:id page

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#423]
<a href="https://github.com/sonejah21"><img src="https://avatars.githubusercontent.com/u/5269893?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sonejah21](https://github.com/sonejah21)**
_Friday Mar 13, 2015 at 16:02 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/283_

----

Use color-coded Font Awesome (or other) icons into status column of Project Orders instead of words. Each icon should have a tooltip that shows us the meaning of the icon. See correlating words/icon list below for status:

- OK (green)
- Warning (orange/yellow)
- Criticial (red circle + white bolt) - see how to "stack" two icons in Font Awesome
- Unknown (blue)
- Pending (light blue circle + white ellipsis) - see how to "stack" two icons in Font Awesome

Here are the icons to use, in the above order:

![uploads/5f01458b-b27d-49cd-bdea-2b232740ffa3/Screen Shot 2015-03-13 at 11.45.02 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5f01458b-b27d-49cd-bdea-2b232740ffa3%2FScreen+Shot+2015-03-13+at+11.45.02+AM.png)

![uploads/6182c64d-599a-4bfc-b0c2-423538924a20/Screen Shot 2015-03-13 at 11.44.42 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6182c64d-599a-4bfc-b0c2-423538924a20%2FScreen+Shot+2015-03-13+at+11.44.42+AM.png)

![uploads/6bc26e6a-345d-46ab-82c8-c5da0cbc3c2a/Screen Shot 2015-03-13 at 11.45.17 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6bc26e6a-345d-46ab-82c8-c5da0cbc3c2a%2FScreen+Shot+2015-03-13+at+11.45.17+AM.png)

![uploads/c5ae05fe-d0f0-4678-9600-87be0a5833ba/Screen Shot 2015-03-13 at 11.46.52 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc5ae05fe-d0f0-4678-9600-87be0a5833ba%2FScreen+Shot+2015-03-13+at+11.46.52+AM.png)

![uploads/bc86e2b8-5638-4eab-986d-991d7ff0b35e/Screen Shot 2015-03-13 at 11.47.23 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbc86e2b8-5638-4eab-986d-991d7ff0b35e%2FScreen+Shot+2015-03-13+at+11.47.23+AM.png)

![uploads/119dbefd-07fe-4ec8-81b2-307440415bf5/Screen Shot 2015-03-13 at 11.18.47 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F119dbefd-07fe-4ec8-81b2-307440415bf5%2FScreen+Shot+2015-03-13+at+11.18.47+AM.png)

**Comment by chriskacerguis** [comment]
<a href="https://github.com/gnklausner"><img src="https://avatars.githubusercontent.com/u/9269960?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gnklausner](https://github.com/gnklausner)**
_Tuesday Mar 24, 2015 at 17:03 GMT_

----

I feel the colors of the icons should match up with the colors of the alerts in the dropdown. In which case, OK should be green, Unknown should be blue. I'm not opposed to changing the colors in the dropdown, though.

**Comment by sonejah21** [comment]
thanks @gnklausner - I have edited the colors above to reflect the dropdown alert colors. muchas gracias.

**Comment by AllenBW** [comment]
we now have colored text that serves this purpose, recommend closing this

**Comment by stackus** [comment]
Works for me.
