### ISSUE TITLE
Entire project card needs to be clickable on "/dashboard" page

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#424]
<a href="https://github.com/sonejah21"><img src="https://avatars.githubusercontent.com/u/5269893?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sonejah21](https://github.com/sonejah21)**
_Friday Mar 13, 2015 at 16:34 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/284_

----

Currently you can open a specific project on the dashboard using the link on the card or using the icon in the middle of the card. The entire card is not a button even though its box-shadow makes it appear that way.

Two things to do: 
1. We need to wrap entire project card contents in a link to the specific project (see blue in screenshot)
2. We need to remove the linking from project name and from the icon itself (see orange in screenshot)

![uploads/88738c36-be00-4895-acb1-b1d0091cfe72/Screen Shot 2015-03-13 at 12.20.34 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F88738c36-be00-4895-acb1-b1d0091cfe72%2FScreen+Shot+2015-03-13+at+12.20.34+PM.png)

**Comment by AllenBW** [comment]
was this reopened intentionally? issue was resolved by  Bug/ux 424 making entire box clickable #484
