### ISSUE TITLE
Create UX for group management

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#427]
Create concept of a group of users in the system.

- [x] Create groups in Admin
- [ ] Add / Remove users from groups
- [ ] Assign groups to projects

Core: https://github.com/projectjellyfish/api/issues/348

**Comment by sonejah21** [comment]
Here's where it's at so far.... 

*Still need to flush out what information we need from an admin to initiate a group to build out the back end and finish the form. 

So far a group has the following data assigned to it via fake data streaming into list_groups_controller.js file: 
- id
- group_name
- group_email
- group_role (user group vs admin group - but we may not need this)
- created_at
- updated_at

When I can have a back-end person assist with this, it will also need to be able to contain the following:
- users
- user_emails
- user_roles
- others??? 

![uploads/735eb4a8-7766-46e7-89e1-e3f340f099f9/Screen Shot 2015-04-09 at 10.47.47 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F735eb4a8-7766-46e7-89e1-e3f340f099f9%2FScreen+Shot+2015-04-09+at+10.47.47+AM.png)

**Comment by chriskacerguis** [comment]
We'll need to add a column that will map the group to an LDAP group, or a SAML attribute.

**Comment by sonejah21** [comment]
Alright cool, thanks! Sounds like back-end work, so I'll let the thoughtbot crew explain it to me/dig into this mapping once I am ready to hand off the front-end. @calebthompson @masonforest

**Comment by sonejah21** [comment]
![uploads/1d3e9e9f-44b7-47d3-b4df-d00a5d8e33c9/add_groups_1.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1d3e9e9f-44b7-47d3-b4df-d00a5d8e33c9%2Fadd_groups_1.png)

**Comment by calebthompson** [comment]
Groups won't have roles at first, and admins should be able to add projects from group management, or groups from project management, whichever you prefer.

**Comment by sonejah21** [comment]
@calebthompson Good idea - I'll add the ability to attach projects to a group into this page. Thanks for that! Since we'll eventually have the ability to add roles, I may just leave the Group Role in this page and disable it. Anything else this page needs?

**Comment by calebthompson** [comment]
Looks good.

**Comment by sonejah21** [comment]
REVISED "Add Groups" page: 
![uploads/91d6abf2-be6f-4a70-92db-52403937e514/add_groups_1b.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F91d6abf2-be6f-4a70-92db-52403937e514%2Fadd_groups_1b.png)

**Comment by calebthompson** [comment]
@sonejah21 I needed to pull in some stuff from this anyhow, so I merged it into my branch. I think we can call this done for now and I'll ping you for help on the other branch/pr when it's functional.

**Comment by calebthompson** [comment]
If that works for you

**Comment by chriskacerguis** [comment]
@calebthompson @sonejah21so I think that the "add project" is not what we need on that screen.  An admin role would add the group to a project (not add the project to a group)

**Comment by sonejah21** [comment]
Sounds good @chriskacerguis ... I'm pulling down Caleb's branch now to include the ui-select, and can remove the Add Projects. I'll post the results later tonight.

**Comment by sonejah21** [comment]
Here's the latest - looks pretty basic, but does the trick. Thanks for the great ui-select in there, @calebthompson - works like a charm :)
![uploads/6130b95e-c384-4706-b414-6ede6f198424/Screen Shot 2015-04-14 at 9.18.57 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6130b95e-c384-4706-b414-6ede6f198424%2FScreen+Shot+2015-04-14+at+9.18.57+PM.png)

**Comment by calebthompson** [comment]
@sonejah21 can you set up some UX for adding projects to groups? @chriskacerguis that probably happens on an admin project page right?

**Comment by chriskacerguis** [comment]
@calebthompson projects aren't added to groups. Groups are added to projects.

**Comment by calebthompson** [comment]
Same concept. We need a page where we select the groups that can access a project.

**Comment by sonejah21** [comment]
Yes, sounds like I'll either add a Projects page under Admin that will house the management of Projects (and could also contain Project Questions that current lives by itself) - or - this would be a section within a Project page that only an Admin can view and have access to. Thoughts?

**Comment by calebthompson** [comment]
I prefer the former as well, but if it's a bunch more work and we're okay with the latter (secret admin area on main project page) we can go with that.

**Comment by sonejah21** [comment]
We've all decided on the main project page being the fastest, easiest way for Adding a Group to a Project. Next step that I'll do from the UX side: Ability to add a group to a project behind the admin flag. (In other words, mirroring the ui-select stuff, including adding a groups collection to the projects for controller.)

**Comment by sonejah21** [comment]
The dropdown of groups is working decently (could use some tweaks to be fully functional).  It now just needs the styling from the latest version of master,  since it's not receiving the correct "form-control" styles.

**Comment by sonejah21** [comment]
Styling of dropdown is good to go now. I removed the descriptions since they might get long. This is cleaner.
![uploads/dca21a1e-bbd8-4fef-8bdb-a639c1dc2cfe/Screen Shot 2015-04-24 at 12.54.42 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdca21a1e-bbd8-4fef-8bdb-a639c1dc2cfe%2FScreen+Shot+2015-04-24+at+12.54.42+PM.png)

Needs:
We need the ability to add a list of groups to the project, not just select one and have it populate the search field.
We need the ability to have the groups saved into the project once selected.

**Comment by calebthompson** [comment]
Resolved by #606, but may need some touch-up.

**Comment by sonejah21** [comment]
This ticket is finished, for the most part. The components that remain have been divided into more tickets.
