### ISSUE TITLE
Product Form needs some Jellyfish-matching UX love (per Britt)

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#429]
<a href="https://github.com/sonejah21"><img src="https://avatars.githubusercontent.com/u/5269893?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sonejah21](https://github.com/sonejah21)**
_Friday Mar 20, 2015 at 19:26 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/300_

----

Per Britt's work on 3/19, the forms need to be matched to our UX.

![uploads/658f74bd-5753-46f2-b067-22aa140beda6/product_form_1.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F658f74bd-5753-46f2-b067-22aa140beda6%2Fproduct_form_1.png)

![uploads/32a96251-e8d1-4769-8edb-ed0c60f3e00c/product_form_2.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F32a96251-e8d1-4769-8edb-ed0c60f3e00c%2Fproduct_form_2.png)

**Comment by calebthompson** [comment]
This is on deck when #466 lands.

**Comment by chriskacerguis** [comment]
Dup of: https://github.com/projectjellyfish/api/issues/540
