### ISSUE TITLE
Add a gray overlay behind Add User modal

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#430]
<a href="https://github.com/sonejah21"><img src="https://avatars.githubusercontent.com/u/5269893?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sonejah21](https://github.com/sonejah21)**
_Monday Mar 23, 2015 at 15:12 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/302_

----

Without the gray backdrop over the rest of the screen, there is too much noise.

![uploads/1198d2b5-1151-4f29-8150-8a39785763de/Screen Shot 2015-03-23 at 10.08.27 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1198d2b5-1151-4f29-8150-8a39785763de%2FScreen+Shot+2015-03-23+at+10.08.27+AM.png)

**Comment by AllenBW** [comment]
Status of this? Unable to replicate, but I am missing the input window in which to search for users...

**Comment by sonejah21** [comment]
Yes it is still needing some love, @AllenBW -  I tried fixing it last week but it was a tricky one and I couldn't get it. Maybe we can join forces on it? I think the complexity comes from some TopCoder hacks.

**Comment by AllenBW** [comment]
rgr, By your powers combined, I a.... We can FIXIT!
