### ISSUE TITLE
Fix the total number of projects 

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#432]
<a href="https://github.com/sonejah21"><img src="https://avatars.githubusercontent.com/u/5269893?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sonejah21](https://github.com/sonejah21)**
_Monday Mar 23, 2015 at 16:13 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/305_

----

Edit this My Projects total # to be a complete circle. It is cut off at the bottom. 

![uploads/fef3166b-ccbb-44d6-87d8-85206d802aa5/Screen Shot 2015-03-23 at 11.11.24 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffef3166b-ccbb-44d6-87d8-85206d802aa5%2FScreen+Shot+2015-03-23+at+11.11.24+AM.png)

**Comment by chriskacerguis** [comment]
<a href="https://github.com/stackus"><img src="https://avatars.githubusercontent.com/u/158579?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [stackus](https://github.com/stackus)**
_Monday Mar 23, 2015 at 16:31 GMT_

----

Heh, I've seen this forever and thought it was supposed to look gumdrop like because "Jelly"fish.

**Comment by chriskacerguis** [comment]
<a href="https://github.com/gnklausner"><img src="https://avatars.githubusercontent.com/u/9269960?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gnklausner](https://github.com/gnklausner)**
_Monday Mar 23, 2015 at 16:34 GMT_

----

At least @stackus seems to appreciate my artistry.

**Comment by gnklausner** [comment]
:sob:

**Comment by sonejah21** [comment]
The bigger, better business client has left me with only remnants of your masterful style. Of which I must change in order for the team to move on. May your adventures be fruitful and may you return to us with newfound wisdom.

**Comment by gnklausner** [comment]
Namaste
