### ISSUE TITLE
Sidebar: Admin's item icons overlap with header icon

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#434]
<a href="https://github.com/gnklausner"><img src="https://avatars.githubusercontent.com/u/9269960?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gnklausner](https://github.com/gnklausner)**
_Monday Mar 23, 2015 at 18:48 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/307_

----

![adminitemsoverlap](https://cloud.githubusercontent.com/assets/9269960/6787787/5ec3cebe-d16b-11e4-8f27-2f79c0865783.png)

**Comment by tangerine007** [comment]
![422-overlap](https://cloud.githubusercontent.com/assets/4211939/6946146/5528656a-d86c-11e4-961a-43c8cd47f3b2.png)
