### ISSUE TITLE
"Add Project Question" and "Edit Project Question" screens need consistency and restyling

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#435]
<a href="https://github.com/sonejah21"><img src="https://avatars.githubusercontent.com/u/5269893?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sonejah21](https://github.com/sonejah21)**
_Monday Mar 23, 2015 at 20:20 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/310_

----

These pages need help: 

- [x] This link to 'Add an Option' on the Add and Edit Project Question pages needs to be styled as a button with proper padding/spacing.
- [x] The titles should be consistent with the rest of the site: in caps. 
- [x]  When Editing a Project Question, the title should say "Edit Project Question", not "Add Project Question"
- [x]  You should be able to delete added Options from the 'Select Option' Field. 

Here is the current screen for editing a Project Question:
![uploads/d9975523-11db-412f-bbeb-6c17b3395cbe/Screen Shot 2015-03-23 at 3.12.04 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd9975523-11db-412f-bbeb-6c17b3395cbe%2FScreen+Shot+2015-03-23+at+3.12.04+PM.png)

Here is the current screen for adding a new Project Question:

![uploads/bafaa650-da04-468f-af8f-ee8676b0e658/Screen Shot 2015-03-23 at 3.13.39 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbafaa650-da04-468f-af8f-ee8676b0e658%2FScreen+Shot+2015-03-23+at+3.13.39+PM.png)

**Comment by sonejah21** [comment]
Added the ability to remove Options when the Field Type "Select Option" is selected. 
If all Option are deleted, kept the first Option present, but cleared, when the "X" is clicked.
Styling changes are in too - may not be final styling, but is better.

![uploads/94e29873-2c0f-428b-94d0-2a40c3566ce4/Screen Shot 2015-04-03 at 6.23.05 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F94e29873-2c0f-428b-94d0-2a40c3566ce4%2FScreen+Shot+2015-04-03+at+6.23.05+PM.png)
