### ISSUE TITLE
Befuddling Error with Back links on Order Details page

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#437]
<a href="https://github.com/sonejah21"><img src="https://avatars.githubusercontent.com/u/5269893?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sonejah21](https://github.com/sonejah21)**
_Tuesday Mar 24, 2015 at 14:11 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/313_

----

When you're in a Project and you click on an Order #, you come to the Order Details page. You see the "<-- Back to Project" link. If you click on it, it works correctly, taking you back to the Project you were just on. See below:

![uploads/b06767f9-1946-4f1e-82d9-856ef07283ed/Screen Shot 2015-03-23 at 4.12.13 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb06767f9-1946-4f1e-82d9-856ef07283ed%2FScreen+Shot+2015-03-23+at+4.12.13+PM.png)

When you refresh this page however, this is where the bug comes in. The refreshed page shows "<-- Back to User Orders" instead of remaining the same as before. When you click on this link it takes you back to the  list of Orders:

![uploads/fdd02e58-f333-4fbc-ba79-76cd2d5e3d9b/Screen Shot 2015-03-23 at 4.12.03 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffdd02e58-f333-4fbc-ba79-76cd2d5e3d9b%2FScreen+Shot+2015-03-23+at+4.12.03+PM.png)

**Comment by chriskacerguis** [comment]
<a href="https://github.com/gnklausner"><img src="https://avatars.githubusercontent.com/u/9269960?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gnklausner](https://github.com/gnklausner)**
_Tuesday Mar 24, 2015 at 14:39 GMT_

----

Line 6 of templates/partials/orders/orders.html is the key.
Line 10 of js/app/base/base_controller.js is also relevant.

**Comment by OBCENEIKON** [comment]
Closing this out as it's no longer an issue. I tested locally and was unable to reproduce and the lines that @gnklausner listed have been changed since then.

**Comment by mafernando** [comment]
@OBCENEIKON - I looked at this a couple days ago, and the issue still persists.

**Steps to Reproduce:**
1. login as admin and navigate to project
![image](https://cloud.githubusercontent.com/assets/9356425/8120758/88b775cc-1068-11e5-8c46-7cd250329ca6.png)
2. Click the Order Id to be take to the Order View
![image](https://cloud.githubusercontent.com/assets/9356425/8120767/a5b1b318-1068-11e5-8566-51e8d275e82a.png)
3. Refresh the page, you will see that the 'Back to Project' button changes to 'Back to User Orders'
![image](https://cloud.githubusercontent.com/assets/9356425/8120773/ba6597ac-1068-11e5-8b27-97dded645765.png)

**Comment by chriskacerguis** [comment]
Not sure this is valid anymore.
