### ISSUE TITLE
Move Rake tasks to rufus

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#441]
So, we need to move the rake tasks that we have to use the new rufus system.  From the install guide

The following rake command needs to be put into Rufus.

````
# Updates the budgets for projects
rake upkeep:update_budgets
````

We don't care about the other 2 jobs at the moment.

**Comment by mafernando** [comment]
@chriskacerguis - do you think that 1 hr intervals are good to run this on?

**Comment by chriskacerguis** [comment]
I'd do, 15 min

**Comment by OBCENEIKON** [comment]
This was pretty much already done, it just needed the line added to the `task_scheduler.rb` file.

**Comment by mafernando** [comment]
Added some feedback to the PR, I think `update_budget` needs some extra love before we schedule it out.
