### ISSUE TITLE
Update Install Guides

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#452]
Go though RHEL install guide and verify.

**Comment by mafernando** [comment]
RHEL 6 install did not work.

Attempted install on CentOS 6.4 with GNOME

Issues:
- Need to run `yum install postgresql-devel` before installing postgresql, specify Postgresql version 9.4 in install and set auth method to md5 
- capybara-webkit requires qt which is not available pre-built. 
 - building qt from scratch can take upwards of *6+ hours*
 - need to install ruby-build not rbenv-build (typo)

**Comment by gnklausner** [comment]
qt is available through apt-get, I'm surprised there isn't something similar for yum...

**Comment by mafernando** [comment]
`yum install qt` installs version 4.6.2 which is below the version required by `capybara-webkit`.
According to [this](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit) Thoughtbot post, we need qt 4.8.x at least for Ruby 2.0.x.
`yum install qt48-qt-webkit-devel` doesn't work [either](https://github.com/thoughtbot/capybara-webkit/issues/560).

A working solution I found which was prescribed by Thoughtbot had me build qt from scratch, but that was time-intensive process.
