### ISSUE TITLE
Fix Safari errors (formerly FontAwesome errors) 

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/api#455]
Safari browsers throw FontAwesome errors. 
May be result in alignment issues or could be completely unrelated.  See ticket #451.

Why are we not using the "font-awesome-sass" gem in our rails app? Maybe that would help.

**Comment by sonejah21** [comment]
@calebthompson - I assigned this to you because I need your advice in tackling it.

**Comment by AllenBW** [comment]
this may be fixed by https://github.com/projectjellyfish/api/pull/457, do a pull check it out (nonmac so I can't say for sure)

**Comment by sonejah21** [comment]
Awesome, @AllenBW and @calebthompson  -> Font Awesome errors gone. 

Now I am seeing new errors:
- "TypeError: Object is not a function (evaluating 'doneCallback()')........ angular-animate.js:993"
- "Unexpected CSS token : "


![uploads/79eeee8c-9e24-4e6c-9b7d-01f4e4de5e0b/Screen Shot 2015-04-01 at 9.58.42 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F79eeee8c-9e24-4e6c-9b7d-01f4e4de5e0b%2FScreen+Shot+2015-04-01+at+9.58.42+AM.png)

**Comment by AllenBW** [comment]
Okie dokie the culprit is  a mismatch of angular version and angular-animate versions for whatever reason ang v is 1.3.15 and ang-animate is 1.2.28  fix incoming....

**Comment by sonejah21** [comment]
Ahhhh i see! Nice. I'm going to reassign this to you for now, @AllenBW. Thanks for getting to the bottom of it. Let me know when the fix is in and I'll re-test.

**Comment by calebthompson** [comment]
I'm AFK but Mason and I fixed this in the product types branch (a tweak to the stuff in master) so I'll take it back.

**Comment by calebthompson** [comment]
Other errors also fixed.

**Comment by AllenBW** [comment]
Oh good, because I can't get a build to pass till that WebKit-safari gem
installs... Or I bail to ubuntu
