### ISSUE TITLE
Unable to run db:migrate when ENV = production

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#463]
When trying to run rake db:migrate when the environment is production, we are getting the following error:

````
[jellyfish@ip-0-0-0-0 api]$ rake db:migrate
rake aborted!
NameError: uninitialized constant Uglifier
/home/jellyfish/api/config/environments/production.rb:28:in `block in <top (required)>'
/home/jellyfish/api/config/environments/production.rb:1:in `<top (required)>'
/home/jellyfish/api/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
````
OS = Red Hat Enterprise Linux Server release 6.6 (Santiago)

**Comment by mafernando** [comment]
Verified that I could run this rake task locally as [production](http://stackoverflow.com/questions/3113828/how-can-i-set-rails-env-to-production-for-all-subsequent-rake-commands):

```shelll
$ RAILS_ENV=production
$ rake db:migrate 
```

Am looking into Heroku logs to verify that Uglifier isn't causing any problems there.

**Comment by mafernando** [comment]
Not sure why, but cannot run `heroku run rake db:migrate` from the CLI toolbelt.

```shell
$ git remote
heroku
origin
$ heroku run rake db:migrate
Running `rake db:migrate` attached to terminal... up, run.2478
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
  ActiveRecord::SchemaMigration Load (1.3ms)  SELECT "schema_migrations".* FROM "schema_migrations"
```

I can access the logs from Heroku, but not run tasks for some reason...some follow-up required here to verify this is not an issue in production.

**Comment by mafernando** [comment]
@chriskacerguis - Attempts run `heroku run rake db:migrate` from toolbelt have not been successful.

I have been able to verify this locally and can see from the last few deployments on Heroku (currently running production mode) that the issue is not actively occurring.

Am tagging this as 'Done' for now.
