### ISSUE TITLE
Create specs for User Stories

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#465]
Create specs for user stories

**Comment by mafernando** [comment]
[Example PR](https://github.com/projectjellyfish/api/commit/d5281359f08f2fa5ae731868d98188b123b2debd)

**Comment by calebthompson** [comment]
Here's the lay of the land: each of these controllers should probably have at least a happy path test. I've omitted things like editing when there's a create form (they're pretty similar), listing and viewing things (often covered by create specs), and less important features like viewing the dashboard (not much to functionally test there).

```
app/assets/javascripts/
├── admin
│   ├── projects
│   │   ├── new_project_question_controller.js
│   │   └── project_questions_controller.js
│   ├── settings
│   │   └── edit_settings_controller.js
│   └── users
│       └── admin_add_user_controller.js
├── cart
│   └── cart_controller.js
├── clouds
│   └── clouds_controller.js
├── dashboard
│   └── dashboard_controller.js
├── marketplace
│   ├── marketplace_controller.js
│   └── show_product_controller.js
├── orders
│   └── orders_controller.js
├── projects
│   ├── edit_project_controller.js
│   ├── new_project_controller.js
│   ├── project_services_controller.js
│   └── project_users_controller.js
├── services
│   └── service_controller.js
├── settings
│   └── settings_resource.js
└── users
    ├── orders
    │   └── user_orders_controller.js
    └── users_controller.js
```

Obviously there's a lot there, so I think we should split this up between several people who would each work on one or two things.

**Comment by mafernando** [comment]
Encountered some issues with writing these specs using Capybara/Poltergeist:
- I could not find the correct syntax to choose an option from the [required](https://github.com/projectjellyfish/api/blob/master/public/templates/partials/admin/projects/project_question_form.html#L41) **Field Type** drop down selector in the [Add Question Form](https://github.com/projectjellyfish/api/blob/master/public/templates/partials/admin/projects/project_question_form.html) under _Admin > Project Questions_.
- I was able to get the `click_on 'ADD QUESTION'` button to work but could not get the `click_on 'SUBMIT'` button to work

I tried removing the validation check on the SUBMIT button to default to `btn btn-primary` instead of evaluating `"projectQuestionForm.$invalid ? 'btn btn-primary disabled' : 'btn btn-primary'"`  
```html
  <div class="form-group">
    <div class="col-sm-10">
        <a type="submit" ng-click="submitFunction()"
           ng-class="'btn btn-primary'">
            {{buttonLabel}}
        </a>
      <a type="button" ui-sref="base.authed.admin.projects.project_questions" class="btn btn-danger">CANCEL</a>
    </div>
  </div>

```
but toggling this did not fix the issue. I know the button is disabled until the all the required form elements are valid, but I thought if I forced the button to be enabled through the UX then it would be available in my rake task. I was wrong.

```
Failures:

  1) Project question creation admin creates a new project question
     Failure/Error: click_on 'SUBMIT'
     Capybara::ElementNotFound:
       Unable to find link or button "SUBMIT"
     # ./spec/features/create_a_project_question_spec.rb:34:in `block (2 levels) in <top (required)>'

Finished in 4.72 seconds (files took 3.58 seconds to load)
```

Example spec for [Add Question Form](https://github.com/projectjellyfish/api/blob/master/public/templates/partials/admin/projects/project_question_form.html) under Admin > Project Questions:

```ruby
require 'rails_helper'

feature 'Project question creation' do
  scenario 'admin creates a new project question', :js do
    new_product_question_attributes = {
        'question' => 'How many unit tests?',
        'help_text' => 'In units of tests',
        'load_order' => 0,
        'required' => false,
        'field_type' => 'Text',
    }

    staff = create(:staff, :admin)
    login_as(staff)
    visit '/admin/projects/questions'
    expect(page).to have_content('Project Questions')
    click_on 'ADD QUESTION'
    expect(page).to have_content('ADD PROJECT QUESTION')
    fill_in 'Question', with: new_product_question_attributes['question']
    fill_in 'Help Text', with: new_product_question_attributes['help_text']
    fill_in 'Load Order', with: new_product_question_attributes['load_order']

    # Tried a few apporaches here but was unsuccessful here
    # find("<option value='text'").click
    # find("option[value='Text']").click
    # select('Text', from: 'fieldType').click
    # select 'Text', from: 'fieldType'
    # find('name=fieldType')
    # expect(page).to have_content('SUBMIT')
    # find_field("Field Type")#.find("option[value='20120905']").click
    # find("option[value='Text']").click
    # select(new_product_question_attributes['field_type'])

    click_on 'SUBMIT'

    expect(page).to have_content('Project question was successfully added.')
    expect(ProjectQuestion.last.attributes).to include new_product_question_attributes
  end

  def selectize(container, option:)
    find("#{container} .selectize-input").click
    find("#{container} #{option}").click
  end
end

```

**Comment by mafernando** [comment]
closing this.
