### ISSUE TITLE
Create Approval Workflows

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#485]
Create a module for Identity and Access Management for Jellyfish.  It should have allow for the following features:

- [ ] Can create custom approval flow for projects
- [ ] Can assign users and/or groups to an approval step.
- [ ] Can assign users and/or groups to role based project access.
- [ ] Can add custom attributes to users.
- [ ] Can assign users to groups based on attribute values.

Other related tickets:

CRUD Groups - https://github.com/projectjellyfish/api/issues/512

**Comment by calebthompson** [comment]
This is a larger feature, I think, than Groups need to be. The first step for them seems like just access to projects, which #512 attempts to capture, then we can circle back and handle approval flows.

**Comment by chriskacerguis** [comment]
@calebthompson that's fair.

**Comment by calebthompson** [comment]
#512 should certainly capture the first two steps: Admin CRUD for Groups, including adding users and projects to groups.

**Comment by sonejah21** [comment]
See JEL-19: https://boozallen.atlassian.net/browse/JEL-19

**Comment by calebthompson** [comment]
hai

**Comment by sonejah21** [comment]
hai caleb!
