### ISSUE TITLE
Enable user to upload Icons/Images

### ISSUE THREAD

**Issue by AllenBW** [projectjellyfish/api#486]
On the edit profile view, an option to upload an icon that will be used through out the PJ.

**Comment by AllenBW** [comment]
This complex task requires a supporting api module to be built out prior to complete implementation.  ng-file-upload is the directive I purpose for implementation on the front end, it will work with both paperclip and carrier wave on the api side: https://github.com/danialfarid/ng-file-upload/wiki/Rails-Example

Next steps as of this moment are to identify the scope of work for the more generic task of file upload, decide if this encompass user icon upload, then allocate resources to build out the functionality in the api.

**Comment by mafernando** [comment]
Another tutorial on using paperclip with rails [here](http://vaidehijoshi.github.io/blog/2015/07/28/clipping-images-for-rails-using-paperclip).

**Comment by sonejah21** [comment]
See JEL-20: https://boozallen.atlassian.net/browse/JEL-20
