### ISSUE TITLE
Project Status Icons "shifted" on Safari

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#489]
![screen shot 2015-04-08 at 9 01 19 am](https://cloud.githubusercontent.com/assets/2414647/7046808/12abc80a-ddce-11e4-9bd6-5b080d8767f8.png)

**Comment by stackus** [comment]
This might save someone time and also find a solution for other cross browser issues. 

UX previously relied on an autoprefixer during the build process to add in any vendor styles not currently supported by the current generation of browsers. To me it looks like the `transform: translate(-50%, -50%)` style isn't being coupled with a `-webkit-transform: translate(-50%, -50%)` style anymore. Does the rails asset pipeline call/use autoprefixer to add these vendor styles?

**Comment by AllenBW** [comment]
rails-asset pipeline does nooooooooot call or use autoprefixer
