### ISSUE TITLE
Move ManageIQ code to module

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#496]
Move ManageIQ code to module

**Comment by calebthompson** [comment]
I don't think it makes sense for me to be assigned here, as I'm working on a different feature set right now.

I think it should be done soon and am happy to review code and offer pointers to whoever does it, but am focused on Groups, etc. stuff for now so it wouldn't be done in a timely fashion.

**Comment by chriskacerguis** [comment]
Repo for module is here

https://github.com/projectjellyfish/jellyfish_manageiq

**Comment by chriskacerguis** [comment]
@OBCENEIKON please make sure you have this as a field in the module

https://github.com/projectjellyfish/api/issues/181
