### ISSUE TITLE
Create Jellyfish-Audit module

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#500]
Need to audit every action.  Then do one of three things with it:

1. Save to local table in JF Database
2. Save to local machine syslog
3. Post JSON payload to a URL

Old Dup ticket: https://github.com/projectjellyfish/api/issues/103

**Comment by mafernando** [comment]
From https://github.com/projectjellyfish/api/issues/103:
<table><tr><td>Extracting useful bits from:<br>
http://rubyjunky.com/cleaning-up-rails-4-production-logging.html<br>
Note: BufferedLogger used in the above example is depreciated in Rails 4, attempting [workaround](http://railsware.com/blog/2014/08/07/rails-logging-into-several-backends/)</td></tr><table>

**Comment by mafernando** [comment]
Creating this gem as a mountable engine because we may want to keep namespaces isolated to resource name conflicts between parent app and engine.

See [this](http://stackoverflow.com/questions/6118905/rails-3-1-engine-vs-mountable-app#answer-6833288) reference.

**Comment by mafernando** [comment]
Actionable Items:
- [ ] Create `jellyfish-audit` repo
- [ ] Save to local table in JF Database
- [ ] Save to local machine syslog
- [ ] Post JSON payload to a URL

**Comment by mafernando** [comment]
Questions Answered:

- [production logging 101](http://rubyjunky.com/cleaning-up-rails-4-production-logging.html) - *rubyjunky*

- [getting started with engines](http://guides.rubyonrails.org/engines.html) - *rubyonrails*

- [engine test setup](http://viget.com/extend/rails-engine-testing-with-rspec-capybara-and-factorygirl) - *viget*

- [engine with rspec & factorygirl](http://www.andrewhavens.com/posts/27/how-to-create-a-new-rails-engine-which-uses-rspec-and-factorygirl-for-testing/) - *andrewhavens*

- [to mount or unmount?](http://stackoverflow.com/questions/6930018/using-classes-in-a-module-from-the-lib-directory-rails-3) - *stackoverflow*

- [using dev gems locally](http://stackoverflow.com/questions/4487948/how-can-i-specify-a-local-gem-in-my-gemfile) - *stackoverflow*

- [engines and migrations](http://pivotallabs.com/leave-your-migrations-in-your-rails-engines/) - *pivotallabs*

- [recent discussion about engines and migrations](http://tech.taskrabbit.com/blog/2014/02/11/rails-4-engines/) - *taskrabbit*

- [testing mountable engines rspec](http://stackoverflow.com/questions/7452037/testing-rails-3-1-mountable-engine-with-rspec) - *stackoverflow*

- [start your engines](https://reinteractive.net/posts/2-start-your-engines) - *reinteractive*

- [jellyfish-ldapauth](https://github.com/projectjellyfish/jellyfish-ldapauth) - *github*

- [jellyfish_fog_aws](https://github.com/projectjellyfish/jellyfish_fog_aws) - *github*

**Comment by mafernando** [comment]
Jellyfish Module Setup (Sample Documentation)
=======
This guide explains how to create a module that can be used with [Project Jellyfish](https://github.com/projectjellyfish/api).

### Step 1: Create Empty Module

Modules in Jellyfish are implemented with gemified [Rails engines](http://guides.rubyonrails.org/engines.html). 

To create a new module named `jellyfish_logger` run:

```shell
$ rails plugin new jellyfish_logger --dummy-path=spec/dummy --skip-test-unit --mountable
``` 

Jellyfish uses [rspec](http://rspec.info/), so exclude test-unit. See [here](http://stackoverflow.com/questions/6118905/rails-3-1-engine-vs-mountable-app#answer-6833288) for a good discussion on mountable engines.

### Step 2: Update Gemspec and Gemfile

##### Populate gemspec

Start by specifying a homepage, summary and description in Gemspec: 
```shell
s.homepage    = "www.projectjellyfish.org"
s.summary     = "Jellyfish Logger Module "
s.description = "A module that adds log support to Jellyfish API"
```

Then replace MIT-LICENSE with APACHE [LICENSE](https://github.com/projectjellyfish/api/blob/master/LICENSE) and switch README to `.md`:
```shell
s.license     = "APACHE"
s.files = Dir["{app,config,db,lib}/**/*", "LICENSE", "Rakefile", "README.md"]
```

##### Add dependencies

Specify un-versioned rails and dotenv dependencies and remove sqlite3 from Gemspec:
```shell
s.add_dependency "rails" 
s.add_dependency "dotenv-rails" # to use env vars from jellyfish api
s.add_dependency 'pg' # to use jellyfish db
``` 

And add these dev and test dependencies to your Gemfile.
```shell
  # DEV + TEST
  group :development, :test do
    gem 'factory_girl_rails'
    gem 'rspec-rails'
    gem 'capybara'
    gem 'rubocop'
  end
```

### Step 3: Setup RSpec

Run `rails generate rspec:install` to add the following skeleton files:
- `.rspec`
- `spec/spec_helper.rb`
- `spec/rails_helper.rb`

Delete `spec/rails_helper.rb` and modify `.rspec` like below to run `spec/spec_helper.rb` before specs and make output pretty:
```
--color
--format documentation
--require spec_helper
```

Then add these lines to `spec/spec_helper.rb`:
```
ENV['RAILS_ENV'] = 'test'
require 'dummy/config/environment'
require 'jellyfish_logger'
```
which mounts this module using the dummy application for specs.

And update `spec/dummy/config/database.yml` to use Postgresql:
```yaml
development: &default
  adapter: postgresql
  database: jellyfish_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

development:
  <<: *default
  adapter:  postgresql
  database: jellyfish_development

test:
  <<: *default
  database: jellyfish_test

production:
  <<: *default
  database: jellyfish_production
```
This file should mirror the [Jellyfish API database.yml](https://github.com/projectjellyfish/api/blob/master/config/database.yml).

### Step 4: Setup Rakfile

Modify Rakefile to look like this:
```shell
begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

APP_RAKEFILE = File.expand_path("../spec/dummy/Rakefile", __FILE__)
load 'rails/tasks/engine.rake'

Bundler::GemHelper.install_tasks

Dir[File.join(File.dirname(__FILE__), 'tasks/**/*.rake')].each {|f| load f }

require 'rspec/core'
require 'rspec/core/rake_task'
desc 'Run all specs in spec directory'
RSpec::Core::RakeTask.new(:spec)
task :default => :spec
```
Notes:
- removed rake statistics reference 
- removed `app:db:test:prepare`

This project uses APACHE LICENSE.

**Comment by mafernando** [comment]
Not sure where to plug this piece in...for some reason, specs don't load ActionController and its LogSubscriber by default (even though we're grabbing `rspec-rails` and `rails`)

In order to use a file that extends the ActionController:LogSubscriber (say an audit client), we need to explicitly require that dependency in the client file like so:

```
require 'action_controller/log_subscriber'

module JellyfishAudit
  class AuditClient < ActionController::LogSubscriber
    def foo
      []
    end
  end
end
```

**Comment by mafernando** [comment]
Regarding this section:

### Step 3: Setup Rakfile

Modify Rakefile to look like this:
```shell
begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

APP_RAKEFILE = File.expand_path("../spec/dummy/Rakefile", __FILE__)
load 'rails/tasks/engine.rake'

Bundler::GemHelper.install_tasks

Dir[File.join(File.dirname(__FILE__), 'tasks/**/*.rake')].each {|f| load f }

require 'rspec/core'
require 'rspec/core/rake_task'
desc 'Run all specs in spec directory'
RSpec::Core::RakeTask.new(:spec)
task :default => :spec
```

Maybe we could move 
```
require 'rspec/core'
require 'rspec/core/rake_task'
desc 'Run all specs in spec directory'
RSpec::Core::RakeTask.new(:spec)
task :default => :spec
```
to the section on RSpec?

**Comment by calebthompson** [comment]
> Follow-up: It seems that we can add require 'action_controller/log_subscriber' to our spec helper instead
> 
> ENV['RAILS_ENV'] = 'test'
> require 'dummy/config/environment'
> require 'jellyfish_audit'
> require 'action_controller/log_subscriber'
> so maybe we should move this here vs to keeping it in the client file?

Since Rails isn't requiring it by default, which we know since we load a Rails app, you'll have the same issue here as you originally did. That should be moved back to the file it's being used in.

**Comment by mafernando** [comment]
I dislike how finicky RSpec can be inside of a module. :(

I moved `require 'action_controller/log_subscriber'` to my spec_helper and removed it from `lib/jellyfish_audit.rb` and I'm running rake now without issue.

Also, I added `config.autoload_paths += %W(#{config.root}/lib)` to my engine so it autoloads all the lib files without requiring me to explicitly include them.

**Comment by calebthompson** [comment]
> I moved require 'action_controller/log_subscriber' to my spec_helper and removed it from lib/jellyfish_audit.rb and I'm running rake now without issue.

Right, and that works because now in your spec_helper, which is required only when running specs, you're loading the file you need, namely action_controller/log_subscriber. Outside of your specs, however, this file won't be loaded because for whatever reason it's not included in the standard rails `require`.

For this to work _outside of specs_, the require line needs to be back in some file required when running `require 'jellyfish_logger'`. The most obvious spot for it to be is in the file where you reference it.

**Comment by mafernando** [comment]
You are correct sir, after playing around with this I did observe that to be the case. 

I did find that adding `require 'action_controller/log_subscriber'` to `spec/dummy/config/application.rb` seemed to work though.

**Comment by mafernando** [comment]
Documentation is now on the wiki:
- [module setup](https://github.com/projectjellyfish/api/wiki/Jellyfish-Module-Setup)
- [add module functionality](https://github.com/projectjellyfish/api/wiki/Add-Module-Functionality)

**Comment by mafernando** [comment]
![image](https://cloud.githubusercontent.com/assets/9356425/7540072/415de952-f571-11e4-8651-0e7ff1a94e19.png)

**Comment by mafernando** [comment]
The `jellyfish-audit` [repo](https://github.com/projectjellyfish/jellyfish-audit) should now have a working module which can be included in Jellyfish API.

The section on adding REST call functionality via module is forthcoming.

**Comment by chriskacerguis** [comment]
Can you please make a ticket for that under that repo?

**Comment by mafernando** [comment]
Done, see [this](https://github.com/projectjellyfish/jellyfish-audit/issues/1) issue.

**Comment by chriskacerguis** [comment]
@mafernando is this ticket "done"?

**Comment by mafernando** [comment]
@chriskacerguis - here are open items that are being tracked as issues in the repo. If that's good with you, then I'm ok with calling this "done".

Actionable Items:
- [ ] Add IP Address to entries - see [this](https://github.com/projectjellyfish/jellyfish-audit/issues/3) issue
- [ ] Add Staff to entries - see [this](https://github.com/projectjellyfish/jellyfish-audit/issues/3) issue
- [ ] Post JSON payload to a URL

**Comment by chriskacerguis** [comment]
Going to close out this issue, since the enhancements are in new tickets in the correct repo.
