### ISSUE TITLE
Spacing off on /marketplace/show/:id

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#506]
In Safari, the spacing is off.

![screen shot 2015-04-10 at 6 34 17 pm](https://cloud.githubusercontent.com/assets/2414647/7099054/6204a852-dfb0-11e4-98f2-dae8f191d8da.png)

**Comment by sonejah21** [comment]
This was a spacing issue that we fixed a few days ago via the autoprefixer, so it no longer is a relevant ticket. (Hooray hooray!)
