### ISSUE TITLE
Add Groups

### ISSUE THREAD

**Issue by calebthompson** [projectjellyfish/api#512]
Group is an object that relates to Staff through Membership, and to Projects. Each of these are `has_many :through` relationships. Users will only have access to Projects through Groups (any existing direct relationships between User and Project will be replaced), which will vastly simplify permissions later.

Admins will create groups and add Staff and Projects to them.

**Comment by chriskacerguis** [comment]
Dup of https://github.com/projectjellyfish/api/issues/485

**Comment by stackus** [comment]
If you haven't considered it I'd suggest allowing the relationship to override the groups initial access level. This way when group access needs to be tweaked a duplicate but slightly different one need not be created. 

Also by still allowing adding a user to a project would allow for overriding any group membership access level they might have been given would further reduce creation of tweaked groups. This could be done the way it is now with some changes, or the membership relation can be altered to have one end use an abstraction or make it polymorphic.

A perfect example of a system which uses groups with no user access and no overrides of access is Github. Because it doesn't offer the flexibility to manage access separate from teams, and because it doesn't allow directly adding a user, owners create dozens of teams with a single user with various access levels that are then tied to different repos.

**Comment by calebthompson** [comment]
Design in #427

**Comment by sonejah21** [comment]
A question: Within the Project page, when you scroll down and currently see "Add User", and clicking it produces a modal with the search input field --- I assume that from our chat (and from the above in this ticket) a single User will no longer be able to be added to a Project. That said, you'd like me to change this "Add User" to "Add Group", and have the search input sift through the group names. The groups selected would then be added to the Project this way. Is that correct @calebthompson? Earlier this morning, @chriskacerguis and I spoke about it being "Add Users/ Groups". And when you'd search in the modal for a group or a user, both users and groups would be shown as possible results to add in. I just want to make sure that both of you are on the same page in terms of how we're handling users.

**Comment by calebthompson** [comment]
Ah, I see the confusion. From the description above, which Chris said seemed right (but might have been missed):

> Users will only have access to Projects through Groups (any existing direct relationships between User and Project will be replaced), which will vastly simplify permissions later.

This makes the logic for connecting users and groups much simpler, and better symbolizes the idea that groups provide access to projects and roles/attributes provide abilities within those projects.

**Comment by sonejah21** [comment]
Ahhh yes, ok. 

I believe you two were speaking the same language. Just wasn't sure when the omission of Add User on the Project page was taking place. For now, I'll simply add the /Group and include the ui-select inside. Hopefully that works for everyone :)

**Comment by calebthompson** [comment]
Cool. @masonforest is working on retrofitting some request specs (the feature spec I used to drive development is already in), we need to add authorization and api descriptions to the new Groups controller, then we can circle back to adding this sometime tomorrow and we're probably ready to PR.

**Comment by sonejah21** [comment]
The "Add User" modal is no longer present in the "groups" branch so I've branched off of master to edit the Add User modal to be the Add User/ Groups. Is this going to merge well with your changes, @calebthompson?

**Comment by calebthompson** [comment]
Nope. The entire structure to connect users and projects directly is gone. Without a bunch of work to back out of that, we don't want Users back on that page. I think you should add just a groups select.

**Comment by chriskacerguis** [comment]
Just following up our conversation.  

People should be able to add users and/or groups to a project

**Comment by sonejah21** [comment]
*** Our Thursday chat recap ***
- Groups are global
- Attach only groups to projects (not users individually)
- A role is then assigned to a group
- All users in the group have that role
- Group permissions per project can vary

**Comment by calebthompson** [comment]
@chriskacerguis, @masonforest and I are running into a technical complexity on that project create failure - after the thread issue is resolved, it’s failing because the project needs to belong to a group the user has access to, which means we need to require that staff add at least one group (presumably one they’re a member of) on project creation. A simpler technical solution would be to only allow Staff.where(admin: true) to create projects, then they’re not related to any staff until they are added to a group, but it means we can deal with the problem without making any more changes to the flow (since there's already a way to add groups to projects). Is that acceptable for this pass?

**Comment by chriskacerguis** [comment]
No, any user must be able to create a project.  Can we have the system create a group called "[project name] Default Group" on creation of a project (in general, not just for the test?)

**Comment by calebthompson** [comment]
That's definitely an option, and not an unreasonable one.

My counter-proposal is that anyone _who is part of at least one group_ can create a project, and they must select one or more groups they belong to to have access. Admins could assign to any group.

I think this is a little better because it shields us from potential new complexity down the road, for example when we have custom Roles in the system and each Group has a Role, how do we determine which role gets added? Or if a user wants to create a project for a group, we'd either end up with an extra throw-away default group or need to add complexity to the controller to create a default group only if there aren't any groups already.

These are just guesses, and may not come up at all. Like I said the default group isn't a bad option just wanted to throw out an alternative and some issues that may arise (I'm sure the picking groups solution would have its own complexity. Authorization comes to mind).

**Comment by chriskacerguis** [comment]
@calebthompson counter proposal acceptable :)

**Comment by calebthompson** [comment]
Resolved by #606
