### ISSUE TITLE
Add User functionality

### ISSUE THREAD

**Issue by EvanBerner** [projectjellyfish/api#513]
When trying to add users to a project, there's a prompt to "enter user's name or email," but no way to actually add that name or email. Also, clicking "add user" tells me users have successfully been added, but should not be able to work since it's impossible to actually enter a user.

**Comment by chriskacerguis** [comment]
@sonejah21 can you investigate, and confirm? This might need to wait until Thoughtbot is done with their current work stream.

**Comment by sonejah21** [comment]
@chriskacerguis I will check on this post-thoughtbot work stream (next week)

**Comment by AllenBW** [comment]
no longer an issue
