### ISSUE TITLE
Order Item ID

### ISSUE THREAD

**Issue by EvanBerner** [projectjellyfish/api#515]
Order Item ID shows as clickable, but nothing happens.
![order id issue](https://cloud.githubusercontent.com/assets/11509735/7122809/c0c52686-e1eb-11e4-85c2-e6d42c06c904.png)

**Comment by AllenBW** [comment]
this works like budda brutha, a click brings up the specifics of the order item AND all other related order items for that project THOUGH, can anyone make comments on the order items below?  looks unrelated to the order selected also unrelated to the project of the order selected, perhaps a view that needs to be removed, need additional thoughts!


![uploads/f91fd152-1435-44f9-921c-20a205ea9400/Capture.PNG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff91fd152-1435-44f9-921c-20a205ea9400%2FCapture.PNG)

**Comment by AllenBW** [comment]
anddddddddddddddd I'm just losing my mind, this is fine ticket will be closed
