### ISSUE TITLE
Project Rejection is not working

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#516]
From mobile team:

"The web interface does not currently seem to support rejecting a project.  If you watch in the inspector, the request that goes out to deny it 404s.  I discovered this trying to determine values for "approval"."

Fairly sure that they are referring to the API when they say "website", BUT I know that the project reject button was not working.  I think that this is the same issue here, but not sure if one is UX and one is API

https://github.com/projectjellyfish/api/issues/419

**Comment by AllenBW** [comment]
hot darn, slaying bugs is what i do, on it tomorrow!
