### ISSUE TITLE
Why push notifications won't work.

### ISSUE THREAD

**Issue by jklarfeld** [projectjellyfish/api#523]
## Why you're hearing about it now
When I saw the initial spec sheet for this app I was under the impression this was a single deployment SAAS product, but after seeing some mockups it quickly became apparent this was not the case.  I assumed someone had come up with a solution for this before it was put on the spec sheet.  Again, this is apparently not the case, so I figured now would be a good time to explain it.

## How APNS Works (Briefly)
*APNS* (Or Apple Push Notification Service) is an inflexible beast.  But the root of the problem comes from the fact that *Project Jellyfish* is meant to be deployed individually by the Corporations choosing to use it.  We'll leave the issues of connecting to APNS from behind a corporate firewall/DMZ aside for now, but the connection requires a one to one paired SSL certificate created in the Apple Developer Program account of the App's (iOS) publisher (which in this case is BAH).  
– You create these SSL CSRs, upload them, and Apple returns you a valid SSL certificate that validates against their own Root CAs for which the creator is the sole owner of the Public/Private key pair that backs them. 
– Apple does not have a copy, and if you lose the key you have to redeploy the app.    
– This SSL certificate is required for the Server backend to connect to APNS (which is a socket connection) and cannot be avoided.
– In the App (iOS), the user must consent to receive push notifications, at which point a request will go to Apple to retrieve a semi-unique (Unique Per App and Device) identifier. Normally, this string is sent back to the backend service for storage and pairing with the User's account in the backend.
– When the backend chooses to send a notification to a user's device, this identifier is used in the body of data sent to APNS.
– When that body of data arrives at APNS, Apple then sends it along to the device. This is one of the highest performance web services in the world and the lag between the original backend sending the request and the push notification arriving on device is measured in milliseconds, even on cellular connections.

## The Problem
Since APNS requires a SSL certificate to receive a connection from the backend, having individual backends sending requests directly to APNS is not possible, as you would have to share this SSL certificate.  This is not only against Apple's ToS but also the same thing as not using SSL in the first place.  The SSL certificate ensures that if someone's cloud deployed instance of *Project Jellyfish* is compromised, it cannot be used to send spam notifications without the password that decrypts the private key backing the SSL certificate.  However, since the backend is written in Ruby and not compiled, that password will be in plain text somewhere, but we'll gloss over that for the time being.

## Is there a solution?
A possible solution for this would be for BAH to provide, maintain, and ensure uptime of a closed source relay to APNS.  An Operator of *Project Jellyfish* would register with you, and when the App (iOS) goes to send the aforementioned unique identifier back to the Operator, the Operator will instead send a heavily authenticated POST request to your relay which will forward the request to APNS when a notification is to be sent.  Amazon pulls off a similar trick with their SNS service (though you provide them with your SSL cert in their case). 

## More Information
– [APNS](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html)

– [Amazon AWS SNS](http://aws.amazon.com/sns/)

**Comment by chriskacerguis** [comment]
This isn't an issue per se.  We'll need to use Amazon SNS.  Going to close this ticket.
