### ISSUE TITLE
Fix the search in Project: Add User modal

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/api#530]
Not allowing for a search to take place in order to add a user to a project.

![uploads/ebbfab12-3b88-4e38-a39f-4a8f735ca7ae/Screen Shot 2015-04-14 at 1.48.50 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Febbfab12-3b88-4e38-a39f-4a8f735ca7ae%2FScreen+Shot+2015-04-14+at+1.48.50+PM.png)

**Comment by AllenBW** [comment]
rocked n socked, fix sitting on a pull request as we speak.

**Comment by sonejah21** [comment]
Thx A.B. Wight.
