### ISSUE TITLE
Create Product "extra" form fields styles don't match existing styles

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#540]
On /admin/products/create, select the "AWS Fog Database" product type the additional fields don't match the existing styles
![screen shot 2015-04-16 at 7 54 14 am](https://cloud.githubusercontent.com/assets/2414647/7181166/ff7d5e4c-e40d-11e4-8bbd-a62e2f6daed8.png)

**Comment by sonejah21** [comment]
Looking to add the styling through the angular-schema-form using the fields offered as Standard Options - see here https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#standard-options

**Comment by AllenBW** [comment]
going to be reworking the style of the whole sheet... wooh!
