### ISSUE TITLE
On /users/orders order totals are $0.00

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#543]

**Comment by AllenBW** [comment]
ok so if you check out the /api/v1/orders totals presented are 0.0, roping in @mafernando for some thoughts on how orders_controller.rb might be changed to deliver SUCCESS

**Comment by chriskacerguis** [comment]
Sending ticket to @mafernando

**Comment by AllenBW** [comment]
@chriskacerguis @sonejah21  

good, now that I have your attention we need to have a hangout talking about this functionality. 

when is the soonest you cool folks can make it in!

**Comment by mafernando** [comment]
TODO:
- [ ] modify orders_controller to return a monthly projection for the `total` attribute - @mafernando
