### ISSUE TITLE
Percent-encoded URLs are not parsed properly

### ISSUE THREAD

**Issue by jklarfeld** [projectjellyfish/api#546]
For example, in `GET /staff?includes[]=projects` from the (documentation)[https://jellyfish-core-build.dpi.bah.com/documentation/1.0/staff/index.html] the URL returns a 404 if you properly percent encode that URL like this: `/staff%3Fincludes%5B%5D%3Dprojects`

**Comment by stackus** [comment]
You won't want to encode the '?' here. The reason to encode it is if you're passing in a '?' as part of a query parameter.
