### ISSUE TITLE
Redundancy of "Add New (Product, Service, User, Group, etc.)" and "Add (Service, Product, etc.)"

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/api#564]
Ideas to play with before solidifying wording:

- Use "Create New (Product, Service, User, Group, etc.)" when generating them from Admin.

or...

- Omit the word Add in the Admin. It would then read " + New Product " or " + New Service " and within a Project, it would remain " + Add Product " or  " + Add Service "

**Comment by stackus** [comment]
I've updated many of the headings to follow the pattern of Action Thing, i.e. Add Product, and Edit Service.

If there exist any that do not fit into this same pattern they need to be updated.

**Comment by sonejah21** [comment]
JEL-21
