### ISSUE TITLE
Creating project failed

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#570]
Build failure in Travis...can you please take a look?

```
Failures:
  1) Project creation staff creates a project
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `admin?' for nil:NilClass
     # ./app/policies/project_policy.rb:53:in `resolve'
     # ./app/controllers/projects_controller.rb:33:in `index'
Finished in 28.91 seconds (files took 12.25 seconds to load)
290 examples, 1 failure
Failed examples:
rspec ./spec/features/create_a_project_spec.rb:4 # Project creation staff creates a project
```

**Comment by masonforest** [comment]
This was failing on the groups branch: I updated the build badge to only show failures on master: https://github.com/projectjellyfish/api/pull/585. Let me know if that isn't what we want. I also fixed the failure on the groups branch here: https://github.com/projectjellyfish/api/commit/493372cf039eda0ab8c7baa61c639cdf57fc1988

**Comment by chriskacerguis** [comment]
@masonforest is this resolved?

**Comment by masonforest** [comment]
Yep! This was resolved by https://github.com/projectjellyfish/api/pull/585
