### ISSUE TITLE
Math for the second circle graph?

### ISSUE THREAD

**Issue by jklarfeld** [projectjellyfish/api#573]
On the Project screen for an Active Project (the one with the two circle graphs), what is the math being used for the second "Time Remaining" graph? The only thing I can think of is: `(currentDate - startDate) / (endDate - startDate)`

**Comment by calebthompson** [comment]
https://github.com/projectjellyfish/api/blob/fix-poltergeist-login-issue/app/assets/javascripts/projects/project_controller.js#L167 It's an estimate based on remaining budget and monthly expenditures.
