### ISSUE TITLE
Determine standard set of product types

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#581]
JF product types are currently configured to align with a *demo* environment.

This marketplace has the following product types:
- Applications
- Big Data
- Databases
- Infrastructure
- Platforms
- Staff
- Storage

To Do:
- [ ] We should determine a *standard* set of product types that JF ships with that can be expanded upon or overridden using modules.

- [x] We need to purge "AWS" and "VMWare" from [questions.json](https://github.com/projectjellyfish/api/blob/master/config/product_questions/questions.json#L2-L50) since they will be added via module/gem.

- [x] The `product_types` hash is implemented [one](https://github.com/projectjellyfish/api/blob/master/config/initializers/product_types.rb#L5) way in JF api and [another](https://github.com/projectjellyfish/jellyfish_fog_aws/blob/master/config/initializers/product_types.rb#L4) way in jellyfish_fog_aws. Make JF api initialize `product_types` like jellyfish_fog_aws.

- [ ] Refactor the way we look up products by product_type to use a helper. It happens at least three times in JF in the [list_projects_controller](https://github.com/projectjellyfish/api/blob/338490dcecad69ff51f221a9be2e9fe78e7f5afd/app/assets/javascripts/admin/products/list_products_controller.js#L10-14), [marketplace_controller](https://github.com/projectjellyfish/api/blob/338490dcecad69ff51f221a9be2e9fe78e7f5afd/app/assets/javascripts/marketplace/marketplace_controller.js#L10-14) and eventually in the [project_services_controller](https://github.com/projectjellyfish/api/blob/feature/fix-add-services-marketplace/app/assets/javascripts/projects/project_services_controller.js#L20-L25)

- [ ] See [this issue](https://github.com/projectjellyfish/jellyfish-fog/issues/1) for work that needs to be done on the jellyfish-fog gem to support his effort.

**Comment by chriskacerguis** [comment]
@mafernando is this still valid?

**Comment by chriskacerguis** [comment]
Not sure that this is still valid.
