### ISSUE TITLE
setup price not added to cart calcs

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#589]
![image](https://cloud.githubusercontent.com/assets/9356425/7417652/18fb2b36-ef2d-11e4-82a9-623cc33796cf.png)

![image](https://cloud.githubusercontent.com/assets/9356425/7417657/2904bec0-ef2d-11e4-9a5f-7e11a656ad4c.png)

**Comment by chriskacerguis** [comment]
We should look at Cart calculations.

**Comment by mafernando** [comment]
we should be able to add a service to a project for a couple days if it fits within a project budget.

a project could have a duration of multiple years, but when determining whether a service is permitted to be added we should only consider how long it will be intended to run.

an expensive server for example, that would only be run for a couple days, should be addable to a project but not project the cost of running for the multiple years the project is scheduled to run

maybe a service/order_item start or end date should be used here?

**Comment by chriskacerguis** [comment]
So, my thought is we don't know how long something will be added to a project for.

**Comment by mafernando** [comment]
i agree - maybe we compute whether something can be added to a project based on the daily cost of setup + hourly?

that way as the spent on the project goes up each day, we have a chance to create alerts and suspend services etc. but then this would require us to know how long a service was active to compute is chargeback contribution.

**Comment by chriskacerguis** [comment]
I think that works.  Perhaps also display a UI warning to the effect of "your project goes from [date X] to [date Y], you do not have enough budget for this service for the full project duration"

**Comment by mafernando** [comment]
i like it. since we're doing a demo walkthrough this upcoming monday, we can hash it out further then.

**Comment by sonejah21** [comment]
@chriskacerguis and @mafernando -

**Comment by sonejah21** [comment]
Accidentally closed this, oops. Just reopened it.

**Comment by chriskacerguis** [comment]
@sonejah21 no, you can derive it from the data we have.

**Comment by mafernando** [comment]
this is now working in api. closing.
