### ISSUE TITLE
revisit/correct cart checkout calculations

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#591]
we should be able to add a service to a project for a couple days if it fits within a project budget.

a project could have a duration of multiple years, but when determining whether a service is permitted to be added we should only consider how long it will be intended to run.

an expensive server for example, that would only be run for a couple days, should be addable to a project but not project the cost of running for the multiple years the project is scheduled to run

maybe a service/order_item start or end date should be used here?

**Comment by chriskacerguis** [comment]
Seems this is a dup of #589
