### ISSUE TITLE
Project "cards" should indicate a "needs approval" state

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#594]
Project "cards" should indicate a "needs approval" state

![dashboard_-_jellyfish](https://cloud.githubusercontent.com/assets/2414647/7419374/4fca7916-ef3a-11e4-9f83-a29e3d56d76f.png)

**Comment by chriskacerguis** [comment]
Errr...maybe use this icon

http://fortawesome.github.io/Font-Awesome/icon/question/

**Comment by sonejah21** [comment]
Sure, I'll throw that in. Might try to get the circle around it too just to be consistent.

**Comment by AllenBW** [comment]
SO Sonja and i had a nice conversation, what are the full range of status
we want to display?  presently each project has a status property.... and
they all say "OK"  the change this bug report references regards the
"approval" property....  so maybe status is an aggregate of a number of
project properties, budget, activity storage (what all those other silly
icons are for on each project button?)

**Comment by sonejah21** [comment]
Here's what I've got based on the "approval":"undecided" and "approval":"approved" statuses. As @AllenBW mentioned, we're wondering what the difference is between the approval and the status of a project.

![uploads/aa3a9ba9-65b0-4cf5-96de-242c068b099a/Screen Shot 2015-04-30 at 2.57.04 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Faa3a9ba9-65b0-4cf5-96de-242c068b099a%2FScreen+Shot+2015-04-30+at+2.57.04+PM.png)

**Comment by AllenBW** [comment]
oh well i believe status is intended to be an aggregate on the full swath
of project properties... we should/could have a varying array of colors to
represent whats the 411 at a glance "FOR CIOS AND DECISION MAKERS"  like
right now blog is approve so it gets green, but say that its thousands over
budget... well that isn't a story told at a glance by this screen!

**Comment by sonejah21** [comment]
Yeah, thinking on this more last night I realized how different approval vs status is. For now, the information we're getting in accurately through the json is the approved and not approved, so that's a start in showing the status. But on top of that, certain projects will eventually have the "critical", "warning", etc. that has its styling set up already, but just isn't rendering due to all statuses for all projects being listed as "ok".
