### ISSUE TITLE
create custom json for order history of projects

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#600]
@AllenBW requested some custom JSON and that's what we're going to give him!

Route should return entries for ALL projects.

![image](https://cloud.githubusercontent.com/assets/9356425/7431690/c25fad6e-efe6-11e4-92a1-15e009460c44.png)

**Comment by AllenBW** [comment]
:+1:

YES PLEASE

**Comment by mafernando** [comment]
Issue https://github.com/projectjellyfish/api/issues/381has some relevant TimeStamp discussions.

**Comment by mafernando** [comment]
[converting to milliseconds](http://stackoverflow.com/questions/4492557/convert-ruby-date-to-integer) since epoch using `to_i` applied onto project created_at timestamp
