### ISSUE TITLE
Integrate CM UX into Jellyfish UX

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#601]
Integrate CM UX into Jellyfish

**Comment by AllenBW** [comment]
- [ ] Update Core to use src/client as 'public/' when env == 'development'
- [ ] Update gulp/config.js to build into the public/ directory
- [ ] If style.css cannot be served from .tmp/ in development it needs to be placed elsewhere (this is separate from the build process)
- [ ] .gitattributes added so the public/ files can be included into the repository and all conflicts ignored.
- [ ]  something something build process created

**Comment by AllenBW** [comment]
- [ ] document ux differences between present vs cm ux  GAP ANALYSIS YO (to be used as a work roadmap for work allocation moving forward)

- [ ] build out authentication (need a login page, implementing routing logic based on success/no success)

**Comment by AllenBW** [comment]
WE DID IT!!!!!!!!!!!!!! #710
