### ISSUE TITLE
Can these numbers be rounded?

### ISSUE THREAD

**Issue by EvanBerner** [projectjellyfish/api#608]
Way too long to make viewing easy
![numbers](https://cloud.githubusercontent.com/assets/11509735/7455626/e92f1c1a-f24b-11e4-97c0-5f2258c73866.png)

**Comment by AllenBW** [comment]
great question!  absolutely, this data is notional and in fact will be
replaced with something special later today :+1:

**Comment by mafernando** [comment]
well done @AllenBW. closing this as its now rounded.
