### ISSUE TITLE
Documentation for New Users

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/api#609]
Step 1: Work with Evan to create documentation divided up by the following categories: 
- [ ]  Install Guide (Getting Started)
- [ ]  User Guides
- [ ]  Contributor Guides
- [ ]  Configuration Guides
- [ ]  API Reference Guides
- [ ]  List of Modules
- [ ]  List of Blueprints
- [ ]  FAQs
- [ ]  Architecture

It will live on http://projectjellyfish.readthedocs.org/en/latest/ and is linked to from the website.

Step 2: 
Create a straightforward, step-by-step Visual Guide to aid Documentation as a Getting Started Guide. This may include screenshots, highlighted segments, etc.

**Comment by mafernando** [comment]
@sonejah21 - we have some documentation sitting in the wiki, will that eventually have to migrate over to readthedocs?

**Comment by sonejah21** [comment]
Oh cool @mafernando, thanks! All I know about are the readthedocs page, the out-of-date website docs pages, and the ReadMe file in github. Could you share the wiki page?

**Comment by mafernando** [comment]
of course, here is the GitHub wiki that we've started to compile.

https://github.com/projectjellyfish/api/wiki :)
