### ISSUE TITLE
Service icons not showing on /project/:id ALSO service remove not functioning properly

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#614]
![screen shot 2015-05-07 at 9 59 15 am](https://cloud.githubusercontent.com/assets/2414647/7518303/c866ecbe-f49f-11e4-9c1a-7e5478ea537d.png)

**Comment by AllenBW** [comment]
Resolved populating service details, ends up remove doesn't work, working to restore that functionality then make a pretty pr!
