### ISSUE TITLE
Project questions confirmation before delete needed

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/api#617]
Two-part enhancement:
1) When you delete a project question, the alert should state which project question was deleted. Right now it is a general alert saying "Project question successfully deleted" - there is no way to know which question you had selected for removal. It should say something like "Project question '<project_question>' was successfully deleted." 
2) Ideally, there would also be an Undo hyperlink after the alert wording in case it was clicked on accident. 
![uploads/4b4302af-41e4-4071-8cfb-21efcbf4fe80/Screen Shot 2015-05-07 at 11.56.09 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4b4302af-41e4-4071-8cfb-21efcbf4fe80%2FScreen+Shot+2015-05-07+at+11.56.09+AM.png)

**Comment by chriskacerguis** [comment]
Not sure we want to go with an 'undo'.  I think that LOE behind something like that would be massive.  Perhaps we could go with a delete confirmation instead?

**Comment by sonejah21** [comment]
Yes that would work too. So the flow would be: 
1) click trash icon; 
2) pop-up (like this, minus the #1 red flag - see Chaotic Moon deck) appears to confirm the deletion; 
3) upon clicking delete, pop-up vanishes and alert appears at top including the project question. 
![uploads/15a3c598-a2fd-4c35-8727-27711ca27a60/Screen Shot 2015-05-07 at 12.08.31 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F15a3c598-a2fd-4c35-8727-27711ca27a60%2FScreen+Shot+2015-05-07+at+12.08.31+PM.png)

Sound good to you @chriskacerguis ?

**Comment by chriskacerguis** [comment]
yep

**Comment by chriskacerguis** [comment]
@sonejah21 is this still valid with the 3.0 UX?

**Comment by sonejah21** [comment]
This has been fixed with 3.0
