### ISSUE TITLE
Fix Group Display on Add New Project form

### ISSUE THREAD

**Issue by chrishample** [projectjellyfish/api#638]
Groups are being displayed on the Add New Project form and the display is odd.

![image](https://cloud.githubusercontent.com/assets/3942492/7616345/b30f92fe-f971-11e4-8b92-858511070660.png)

When adding a new project, should users be able to add groups at that point?  If that was what was intended it sort of makes sense once the UI is fixed.

**Comment by calebthompson** [comment]
duplicate
