### ISSUE TITLE
Create Pre Flight Env Check

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#647]
Add functionality that checks to see if all environment variables needed for loaded modules are set

To Do:
- [ ] Add `pre-flight-env-hash` to Rails [x namespace](http://guides.rubyonrails.org/4_2_release_notes.html#railties-notable-changes) which will be used to verify all environment vars are set 
- [ ] Update [module docs](https://github.com/projectjellyfish/api/wiki/Jellyfish-Module-Setup) to add instructions to update the `pre-flight-env-hash` in their initializer
- [ ] Update [module docs](https://github.com/projectjellyfish/api/wiki/Jellyfish-Module-Setup) to specify that environment variables should be prefixed with `jellyfish_`

**Comment by chriskacerguis** [comment]
This is no longer needed.
