### ISSUE TITLE
Adjust styling for Groups input in project/:id and project/new

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/api#648]
Adjust the input positioning and sizing in project/:id and project/new. Both have the input located beneath the title "Groups".

![uploads/3f58d50a-c163-44a7-aecd-21b8b92989a4/Screen Shot 2015-05-18 at 11.45.31 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3f58d50a-c163-44a7-aecd-21b8b92989a4%2FScreen+Shot+2015-05-18+at+11.45.31+AM.png)

**Comment by sonejah21** [comment]
I edited the groups_input.html and other html files affected by Groups with styling to match our application. The following html files were affected: 
- Add Group & Edit Group: these forms now contain a basic Group Role select dropdown. Still needs functionality.
- Add Project & Edit Project: see below
- Project page (/project/:id): see below

![uploads/f4346742-3b82-483e-a0d6-abe6449601b1/Screen Shot 2015-05-20 at 2.05.39 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff4346742-3b82-483e-a0d6-abe6449601b1%2FScreen+Shot+2015-05-20+at+2.05.39+PM.png)

![uploads/164559b6-f847-4e98-9445-a80ea0cc2306/Screen Shot 2015-05-20 at 1.59.45 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F164559b6-f847-4e98-9445-a80ea0cc2306%2FScreen+Shot+2015-05-20+at+1.59.45+PM.png)

![uploads/e9e03696-699d-4524-aa39-e12a86ca1c18/Screen Shot 2015-05-20 at 1.58.58 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe9e03696-699d-4524-aa39-e12a86ca1c18%2FScreen+Shot+2015-05-20+at+1.58.58+PM.png)

![uploads/96792941-735b-4b28-919b-62434406cc2f/Screen Shot 2015-05-20 at 1.57.20 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F96792941-735b-4b28-919b-62434406cc2f%2FScreen+Shot+2015-05-20+at+1.57.20+PM.png)

**Comment by sonejah21** [comment]
Changing the styling of selected groups - not using the card look anymore, going for something closer to this stacked <li> look...
![uploads/5ca24736-5430-4edb-ab94-c053624220f0/Screen Shot 2015-05-21 at 12.36.31 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5ca24736-5430-4edb-ab94-c053624220f0%2FScreen+Shot+2015-05-21+at+12.36.31+PM.png)

**Comment by sonejah21** [comment]
WIP - here is where styling is at for the list of groups in a Project.
Left to do:
1) In Admin > Groups html, make the Remove/Delete red button function (to delete a group) using a double confirmation (modal perhaps) and post-deletion, an alert confirmation. 
2) Style the list of options within the Select dropdown
3) Figure out the width of the entire list (currently at col-sm-12, or almost 100% screen width)
4) Any sort of visual to add into the list of groups that represent type of group (role)? That would be nice - see above. 

![uploads/84c05284-5ce1-4ff4-88a5-33d515c4810e/Screen Shot 2015-05-22 at 4.49.29 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F84c05284-5ce1-4ff4-88a5-33d515c4810e%2FScreen+Shot+2015-05-22+at+4.49.29+PM.png)

**Comment by sonejah21** [comment]
Need to merge in Caleb's Roles with my Groups input stuff. WIP.

**Comment by chriskacerguis** [comment]
No longer valid with 3.0 UX
