### ISSUE TITLE
Headers in Project Alerts need a min-width.

### ISSUE THREAD

**Issue by OBCENEIKON** [projectjellyfish/api#665]
When resizing the page, text is wrapping.
![image](https://cloud.githubusercontent.com/assets/164630/7861393/7052fcbc-0515-11e5-942c-d3da336f17fc.png)

**Comment by OBCENEIKON** [comment]
This issue appeared during a demo with ManageIQ.

**Comment by mafernando** [comment]
@AllenBW - do you know if this persists in the new UX?

**Comment by mafernando** [comment]
This issue exists in the current UX, but have verified with Allen that it will not persist in the new UX. Closing this for now.
