### ISSUE TITLE
/marketplace should indicate what cloud (in column)

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#716]
/marketplace should indicate what cloud (in column) that service resides in

**Comment by AllenBW** [comment]
by cloud do you mean provider?   this has me thinking.... right now most information we display comes from the name or description, maybe we should break it down a bit more (a product) to also have provider or cloud field?

**Comment by chriskacerguis** [comment]
Cloud Provider = AWS, Azure, VMware, etc.

**Comment by AllenBW** [comment]
so thoughts on making this be a dedicated field for a product? call it product_provider or something like that?

**Comment by chriskacerguis** [comment]
That would work.  Have @stackus add this (he's working on the Products right now)

**Comment by AllenBW** [comment]
Will work this once the product_type endpoint is live @stackus

**Comment by AllenBW** [comment]
Quick pulse check on what ever came of this... adding product provider to the product endpoint

**Comment by stackus** [comment]
The information is provided by the product type.

**Comment by AllenBW** [comment]
Given that products are grouped by type, I have no cause to duplicate the information in a table column
