### ISSUE TITLE
On /order-history unclear on where to click 

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#718]
On /order-history it seems to be unclear on where to "click" to get the info (currently you have to click on the ID#). Let's add a button that says "Details". It should look similar to how things are on the /projects/:id/add-services page

**Comment by mafernando** [comment]
Implemented in PR https://github.com/projectjellyfish/api/pull/802.

**Comment by mafernando** [comment]
merged, closing.
