### ISSUE TITLE
Dashboard isn't loading on login

### ISSUE THREAD

**Issue by OBCENEIKON** [projectjellyfish/api#719]
After successfully logging in, the dashboard is blank.

**Comment by OBCENEIKON** [comment]
It looks like an API issue, the request is empty.

![image](https://cloud.githubusercontent.com/assets/164630/8185612/06ece76a-140b-11e5-9b78-42a1b81ddcaf.png)

**Comment by AllenBW** [comment]
not an issue, dashboard isn't in play yet.
