### ISSUE TITLE
/order/:id/service/:id needs to be enhanced

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#720]
/order/:id/service/:id needs more details about the service

- [ ] Billing History
- [ ] More info about the service

More to come

**Comment by AllenBW** [comment]
i believe this endpoint has been TERMINATED, details of a service are accessed on the project details page by selecting a service idea in the order history list.   pricing is included  and project details, which is all that is presently available info on a service

a note to the architects, all this other stuff as a param on to: api/v1/services/:id

**Comment by sonejah21** [comment]
JEL-23
