### ISSUE TITLE
Edit Project button doesn't work

### ISSUE THREAD

**Issue by OBCENEIKON** [projectjellyfish/api#721]
It looks like a angular issue, the ui-sref is `<a ui-sref="projects.edit({projectId: vm.project.id})" class="btn-rounded">Edit Project</a>`

**Comment by AllenBW** [comment]
noticed this earlier on it now

**Comment by AllenBW** [comment]
no longer an issue!

**Comment by OBCENEIKON** [comment]
No longer an issue.
