### ISSUE TITLE
Can't add items to cart

### ISSUE THREAD

**Issue by OBCENEIKON** [projectjellyfish/api#722]
In the marketplace, I can't find anywhere to add items to my cart.

**Comment by AllenBW** [comment]
you using the heroku instance or local?

**Comment by OBCENEIKON** [comment]
heroku

**Comment by stackus** [comment]
This is expected. You can only add services to an approved project. The marketplace is just a showroom.

**Comment by chriskacerguis** [comment]
Perhaps we can add some kind of message indicating this?

**Comment by mafernando** [comment]
@AllenBW had a good suggestion last week to put the error message in the cart modal. Maybe that could be an option here?

**Comment by stackus** [comment]
The cart no longer exists.
