### ISSUE TITLE
Project Pending alert of /projects/:id to match aesthetic of 3.0

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/api#723]
Upon creating a new project, the "Project Pending, Requires Approval or Rejection" shows up larger and bolder than even the title of the project on top. 

Edit this to match the sleek 3.0 aesthetic (not bold, maybe all caps in smaller font). 
Also, in an ideal world the input field would only show up after REJECT has been clicked. 

![screen shot 2015-06-16 at 10 40 45 am](https://cloud.githubusercontent.com/assets/5269893/8185874/d65ffe02-1414-11e5-9f50-d8830088b41c.png)

**Comment by stackus** [comment]
See comments on #731

**Comment by AllenBW** [comment]
closed as was addressed in #731
