### ISSUE TITLE
"Description" discrepancy on /projects/:id

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/api#724]
After creating a new project, with a project Description, the first line of the Details box - entitled "Description"- on /project/:id is blank. 
![screen shot 2015-06-16 at 10 52 39 am](https://cloud.githubusercontent.com/assets/5269893/8186048/ea4faba0-1415-11e5-8404-ff9101ced7f0.png)

If you scroll down though, and look see the "Project Description" of the Project Questions, the description is included there. 

Are these different descriptions or are they the same? Why is one filled in and the other not? 

![screen shot 2015-06-16 at 10 49 13 am](https://cloud.githubusercontent.com/assets/5269893/8186053/eea368f4-1415-11e5-88e8-ec55cfa66d02.png)

**Comment by stackus** [comment]
There's some demo project question that asks for the description.

However the real issue here is that the columns for the project-questions table need to be defined with maximum widths. The question and answers columns shouldn't force others to squish.

**Comment by AllenBW** [comment]
this has since been resolved, closing.
