### ISSUE TITLE
Adding group shows empty curly braces

### ISSUE THREAD

**Issue by OBCENEIKON** [projectjellyfish/api#725]
When attempting to add a group in the admin panel, below the save button is an empty set of curly braces.

![image](https://cloud.githubusercontent.com/assets/164630/8186231/a6959eee-140e-11e5-881d-3e766e86db67.png)

**Comment by OBCENEIKON** [comment]
Actually, it's a JSON representation of the group to be created.

![image](https://cloud.githubusercontent.com/assets/164630/8186261/d93e2190-140e-11e5-8c8d-8b6fb6e18074.png)

**Comment by AllenBW** [comment]
yep, not finished, known issue.
