### ISSUE TITLE
"Projected Total (Monthly)" lacking readability on /order-history/:id 

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/api#726]
The "Projected Total (Monthly)" should be on one line. The spacing with the bold styling is not good for ease of use. 

If it is too long for one line (i.e. it makes the other titles above/below too far from the project information) then I recommend changing it to "Monthly Estimate" or "Estimate (Monthly)".

![screen shot 2015-06-16 at 10 55 51 am](https://cloud.githubusercontent.com/assets/5269893/8186150/938182fc-1416-11e5-816e-29c60743d52e.png)

**Comment by stackus** [comment]
I've refactored this page to be in the 3.x style.

I'll update this issue once the branch is passing and I've merged it in.

**Comment by stackus** [comment]
Fixed by pr #714
