### ISSUE TITLE
Adding a product gives a JavaScript error

### ISSUE THREAD

**Issue by OBCENEIKON** [projectjellyfish/api#730]
Attempting to add a "Databases" product, this JavaScript error is thrown.

![image](https://cloud.githubusercontent.com/assets/164630/8186529/6000bbf6-1410-11e5-8a37-b9e498f69a6d.png)

**Comment by stackus** [comment]
Note to fixer: 

The new UX is expecting the product_type custom fields to be in a different place. It'll be easier to have UX look in the right place.

**Comment by chriskacerguis** [comment]
@AllenBW can you please take a look here

**Comment by AllenBW** [comment]
Awaiting a product_type fix from Stack! Will retouch after his changes go through.
