### ISSUE TITLE
Project Details page post-rejection needs styling - /projects/:id

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/api#731]
If you don't provide a reason when rejecting a project, you get this view when clicking on the project.
![screen shot 2015-06-16 at 11 12 48 am](https://cloud.githubusercontent.com/assets/5269893/8186635/6126398a-1419-11e5-8803-1a88a5fa773b.png)
A few things: 
- It could say "Admin Staff rejected: No reason provided." instead of just "Admin Staff: "
- Perhaps the entire page could also have a deactivated appearance.
- When you go back to the list of projects, it's APPROVAL status is still blank. This should be an "X" to indicate it was rejected. See below.
![screen shot 2015-06-16 at 11 22 55 am](https://cloud.githubusercontent.com/assets/5269893/8186788/56bdb878-141a-11e5-8726-dcd63534563b.png)

**Comment by stackus** [comment]
Notes:

The rejection button should be disabled if the rejection message is empty. For the 'X' use the ic_ asset for the red 'X'.

**Comment by AllenBW** [comment]
that button TOTALLY used to be disabled before, reworking this now.
