### ISSUE TITLE
Create Project - "Start Date" and "End Date" - alignment off post-save (with no dates)

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/api#734]
1. Should be "An end date is required", not "A end date is required".
2.  The alignment of the calendar icon box and input box is thrown off when no dates are selected. This required statement should come on a brand new line, just like the above Project Name and Budget.

Another thought: The project questions below do not have text telling you it is required. It relies on the top "PLEASE COMPLETE REQUIRED FIELDS IN RED" and the red outlines. So another option in dealing with this is that we could omit the specific lines that appear below the inputs which ask for project name, budget, start date and end date. Everything could just be outlined in red. 

![screen shot 2015-06-16 at 11 37 53 am](https://cloud.githubusercontent.com/assets/5269893/8187127/38ba056e-141c-11e5-9750-bbcdf60b6170.png)

**Comment by stackus** [comment]
The date fields also require the correct styling. And shouldn't get nudged when the error text is displayed.

**Comment by AllenBW** [comment]
pr #752  resolves
