### ISSUE TITLE
Mktplace Compare modal: Add icons to Products; Add border 

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/api#738]
The Marketplace's Compare modal would look more attractive with the following additions:
1. Add the icon into the title of the Service being compared. See below (orange arrows). 
2. Add a nice border to match the Cart modal view so it does not appear cut off and matches the other modal. 
![screen shot 2015-06-16 at 1 00 03 pm](https://cloud.githubusercontent.com/assets/5269893/8189164/694572fc-1428-11e5-8c32-0fd6879ca459.png)
Here is the cart's border for reference:
![screen shot 2015-06-16 at 1 02 16 pm](https://cloud.githubusercontent.com/assets/5269893/8189177/895313ec-1428-11e5-8d7a-aadbfc5d9d8c.png)

**Comment by stackus** [comment]
The last row in the compare dialog is being hidden when the user cannot add items to the cart. I'm aware of this and will be working on putting some sort of footer on the modal in the future.

**Comment by sonejah21** [comment]
JEL-24
