### ISSUE TITLE
Saving alerts doesn't save

### ISSUE THREAD

**Issue by OBCENEIKON** [projectjellyfish/api#751]
Editing just loses changes, creating gives a 500.

**Comment by chriskacerguis** [comment]
@mafernando is working on the alert system

**Comment by chriskacerguis** [comment]
@mafernando can you comment on this?

**Comment by OBCENEIKON** [comment]
I've commited a branch fixing the 500, it's failing tests though with all the recent changes.

**Comment by chriskacerguis** [comment]
@OBCENEIKON can you coordinate with @mafernando

**Comment by mafernando** [comment]
@OBCENEIKON - please hold off on doing stuff with alerts for now. 

https://github.com/projectjellyfish/api/issues/138

I'm trying to work out what the right way to refactor alerts is.

**Comment by mafernando** [comment]
Fixed with PR https://github.com/projectjellyfish/api/pull/783.
