### ISSUE TITLE
Token Authentication is non-functional/changed.

### ISSUE THREAD

**Issue by jklarfeld** [projectjellyfish/api#763]
It took me a while to notice this, but despite the fact that/staff/sign_in does indeed return a token, it cannot be used.

When using this token in the `X-STAFF-TOKEN` header field in a request (code unchanged from before) every request returns a 401.  

Apparently, the service still returns a cookie and will favor that over the token, even if a token is present.  Once you completely disable cookie acceptance in the iOS code base, this issue becomes noticeable, as apparently Cookie auth was working transparently for a while.  When you redeploy an iOS app however, all cookies are removed, preventing you from being able to authenticate again.

So either token auth is completely non-functional,

**OR**

The header key has changed, and is no longer `X-STAFF-TOKEN`

**Comment by stackus** [comment]
@jklarfeld I've verified that the token authentication did change, and then was also broken. I will have an update shortly. I will have instructions on proper token authentication at that time as well.

**Comment by stackus** [comment]
@jklarfeld Token Usage

### Sign-In
1. Sign-in at `POST api/v1/staff/sign_in.json`
    `{staff: {email: "...", password: "..."} }`
2. Grab and keep the `api_token` from the response
3. Add an 'Authorization' header with the value of `Jellyfish {api_token}`
  or
Add a url parameter of `access_token={api_token}`

If your cookie is deleted it will be recreated as long as the next request includes a valid token.

### Sign-out
1. Sign-out at `DELETE api/v1/staff/sign_out`

The token will be invalidated along with the session.

**Comment by jklarfeld** [comment]
And we're 100% sure this works completely without cookies? Is there any reason one needs to be returned or even checked for? 

Because the goal here is to pretend we live in a world where there's no such thing as cookies.

And the bug was that if a cookie was present the token was ignored.  Is this still the case?  I have cookies completely disabled in the app, just for my own reference.

**Comment by stackus** [comment]
Yes, it works without cookies. 

If the session cookie exists then that will be used to authenticate the user, otherwise it will use token authentication if a token exists. This remains unchanged.

The reason you're going to be getting a session cookie is because the server supports other methods of authentication which requires that session cookie ability to be active.
