### ISSUE TITLE
Memberships API is non-functional

### ISSUE THREAD

**Issue by jklarfeld** [projectjellyfish/api#764]
Based on the documentation [here](https://jellyfish-core-build.dpi.bah.com/documentation/1.0/memberships/create.html), either a `POST http://jellyfish-core-build.dpi.bah.com/api/v1/projects/4/groups/1` OR `POST http://jellyfish-core-build.dpi.bah.com/api/v1/projects/4/groups?group_id=1` , where "4" is the project id (that exists) and "1" is a group id (that exists), should add a group to the specified project.

However, both of these methods return `500`.

Additionally, there does not appear to be a web-based interface to this, nor are there any groups shown for a project in the web interface.

Finally, the documentation is incorrect as it displays differing methods for accomplishing this task.

**Comment by stackus** [comment]
The documentation was incorrect and the example appears to also be from an early run.

Make your POST request to `api/v1/projects/:project_id/groups` with a payload of `{group_id: ...}` and the membership will be created and the new object returned to you.

Group membership UI is in development.
