### ISSUE TITLE
Groups section missing from projects details page

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#769]
Groups region is missing.

- 'Add Group' button should open a small modal (see product type selection modal for direction and service/directive code)
- Table should show group name, member count, and remove icon.
- TBD where the name should link to if at all.

**Comment by AllenBW** [comment]
the the third bullet, a groups details view, showing what members are part of that group and the description (maybe move the edit to here also)

actually we might want to add description on the groups table,  or somewhere, relying on only group title feels no bueno... for a brand new user, the only way to know all there is to know about a group is to click edit right now

**Comment by AllenBW** [comment]
satisfied by pr #777
