### ISSUE TITLE
Address crash to login in UX

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#782]
Right now when the application receives an error response from the server the user is sent back to the login screen. An error screen should be created and have the user sent there instead. Their session is likely fine and the error may be recoverable. 

* Have the error page display upgraded severity if user continues to run into errors.

To accomplish the following needs to happen

- We need to catch non 2xx status codes during a state change `resolve`. This is done with the `$stateChangeError` message. So a handler needs to be placed there. This code should live within the routerHelper.
- To avoid locking the application into an endless loop trying to route the user anywhere we also want to keep track of the times the handler has caught an error and abort if a loop is detected.
- If the error is recoverable, likely not in a loop, then it should offer a way back to the application.

See this wiki for information on ui-router state error handling : https://github.com/angular-ui/ui-router/wiki

**Comment by OBCENEIKON** [comment]
I don't think this is an issue anymore? I got a modal window when an error 422 was returned.

![image](https://cloud.githubusercontent.com/assets/164630/8758295/0b506a92-2ca8-11e5-972a-51ef37bb0df2.png)

**Comment by stackus** [comment]
It will still go back to the login if the error goes unhandled.

**Comment by OBCENEIKON** [comment]
Wouldn't we need to somehow need to cache the number of times a user encounters this error, and auto expire after so many minutes?

**Comment by stackus** [comment]
If we incremented the count in the handler and then cleared it in `$stateChangeSuccess` that should work for our count.

**Comment by stackus** [comment]
State errors are better handled in the refactored UX.
