### ISSUE TITLE
Product descriptions are not clickable

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#795]
The `product-description` directive allows you to pass in a `link-to` state but it's missing from several places around the application.

- [ ] Find all uses of `<product-description` and be sure there's a correct `link-to`.

**Comment by AllenBW** [comment]
wouldn't need to change it in all the places, only like 36 of product-description.directive.js

where do we want these things to point? presently a product details page doesn't exist (only services) 

you want me to add a details state to marketplace? (would be the most logical place to put it)

**Comment by stackus** [comment]
Careful here. I mentioned two different directives proDUct and proJEct. The proDUcy directive allows you to pass in a state via link-to. Any edit you make should be external to the directive itself.

You'll need to have the services table link to the service details for that listing.

**Comment by AllenBW** [comment]
sorry misspelling in original post, the directive defines a state as default that does not exist on line 36 "products.details'  rather than changing each instance of <product description> i plan to change the default instead and add a details view to the marketplace state, (where the default will redirect)

**Comment by stackus** [comment]
Add a `products.details` state leaving the default as is. The use of the directive in the services table for a project should still go to a service details page.

**Comment by AllenBW** [comment]
ok

**Comment by AllenBW** [comment]
pr #810
