### ISSUE TITLE
No product properties are being displayed

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#798]
Different products have different properties or attributes. These extra properties are not being displayed in the compare modal or in the product and services details pages.

- [ ] Send properties to UX from API
- [ ] Display properties in the compare modal
- [x] Display properties on the product details page
- [ ] Display properties on the service details page

**Comment by AllenBW** [comment]
On the service details page, are we wanting to show provisioning answers?  or what additional details are desired? Presently provisioning answers is not a valid method on the services controller.

**Comment by stackus** [comment]
This has been resolved by the new product work.
