### ISSUE TITLE
Roles cannot be applied to memberships

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#799]
When adding a group you're not able to select the role that group has on the project. Will also need a way to edit the role on a membership.

- [x] Add a select to choose the role to the membership modal
- [x] Display the role in the memberships table
- [x] Add an edit action to update the membership so the group or role can be changed
- [x] The group select in the membership modal isn't the correct height, it may be missing a class
- [x] The alignment of the group name in the table is not aligned with the header for that column

**Comment by AllenBW** [comment]
So that I understand, roles are added to groups on a per project basis?

**Comment by stackus** [comment]
Yeap.

**Comment by AllenBW** [comment]
regarding: "Add an edit action to update the membership so the group or role can be changed"...

we have admin pages for this sole purpose, seems a little muddled to duplicate this functionality on the project details page...

**Comment by stackus** [comment]
Memberships have three foreign keys. `staff_id`, `project_id`, and `role_id`. The only time it is appropriate to fill in all three is in some way from the project edit page.

There isn't akaik a page where memberships can be viewed in mass and changed.

**Comment by AllenBW** [comment]
yep i'm on board with that, what I was asking is if you are looking to edit exiting roles or groups from this page, sounds like the answer is no

**Comment by stackus** [comment]
Correct, only looking to edit the membership so the assigned role can be changed.

**Comment by AllenBW** [comment]
SAME PAGE, that's where we are.

**Comment by AllenBW** [comment]
pr #820
