### ISSUE TITLE
Price columns aren't that helpful

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#800]
Showing all three prices isn't turning out to be that helpful in the marketplace and the Price column in the cart is confusing.

- [x] Display a single Monthly Price, `monthly_price + (hourly_price * 750)`, in the marketplace
- [x] Rename the Price column in the cart to Monthly Price
- [x] Add a Setup Price to the cart

**Comment by AllenBW** [comment]
the value 750?  is it hours in a month? isn't that closer to 730?

**Comment by chriskacerguis** [comment]
It's a commonly accepted practice for all the cloud providers to use 750 hours for hours in a month.

**Comment by AllenBW** [comment]
and now i know, thanks!

**Comment by AllenBW** [comment]
pr #848
