### ISSUE TITLE
https://jellyfish-core-build.dpi.com appears to be semi-down?

### ISSUE THREAD

**Issue by jklarfeld** [projectjellyfish/api#807]
So when testing issues #763 and #764, I was able to get the sign in to work once, and then the server appears to be offline.  I get back warnings from the OS telling me the hostname couldn't be resolved, which also occurs in the browser.  

I tried the same request from cURL and I get back "Could not resolve host" as well.  What's interesting, is if I try this in a new browser, I can see the sign in page once.  

However, if I quit this browser and return it says "could not resolve".

Additionally, occasionally when I try to hit the API from the browser, it will bounce me to the login page regardless of what I try to access (which is expected).  I also attempted to append `access_token=` to the header with one of the tokens I'd received previously.  This will get me the data from that particular endpoint, and if I try to load `/staff/sign_in` again, I will be auto signed in (I'm guessing because I got a cookie back from the previous request that worked).

So my guess here is, something is messed up with the cookie auth at the DNS level.  Either way, not being able to POST the login from cURL means I can't do this from iOS either.  That said I did get it work once from cURL, but not again.

**Comment by chriskacerguis** [comment]
Can you please try with this URL:

https://jellyfish-core-dev.herokuapp.com/login

**Comment by jklarfeld** [comment]
This URL appears to work, I'll update if I find any other issues
