### ISSUE TITLE
"Create Project" form requires me to enter a non-required field

### ISSUE THREAD

**Issue by jnegrelli** [projectjellyfish/api#811]
Filled in new project details except for "Maintenance Day," "Project Charge Code" and "Project Description."
Form failed, highlighting the missing required fields which included "Project Charge Code" and "Project Description."
Filled in those two fields, but "Save" button would not light up until I also picked a "Maintenance Day."

##### Repo steps
1. Begin with creating a new `Project`.
2. Leaving `Maintenance Day`, `Project Charge Code`, and `Project Description` blank, enter values for all fields
3. Click `Save`
4. Correct invalid fields

Save button will not re-enable.

**Comment by OBCENEIKON** [comment]
This has been fixed in a previous commit, following the steps listed by the user results in the save button re-enabling.
