### ISSUE TITLE
Product Types Need Provisioning Answers in UX

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/api#827]
The provisioners in the Jellyfish Fog gem look for provisioning answers into order to specify the custom attributes needed for  a service to be deployed. Currently, those questions are not being populated in the UX for creating/editing Products from Product Types.

**Steps to Reproduce:**

Select a new Product Type to instantiate a new Product instance with from Admin > Products:
![image](https://cloud.githubusercontent.com/assets/9356425/8626240/48d958aa-2709-11e5-971b-cdace6fe8d64.png)

**Issue:**

The create/edit form is missing the associated Product Type questions. 
![image](https://cloud.githubusercontent.com/assets/9356425/8626587/039d5d48-270b-11e5-9ed2-aa59b60e99e7.png)

In the case of AWS Fog Infrastructure, the [product type questions](https://github.com/projectjellyfish/jellyfish-fog/blob/master/config/product_questions/aws_infrastructure.json) should be populated with the following:
![image](https://cloud.githubusercontent.com/assets/9356425/8626480/ab8abc86-270a-11e5-8bb9-2bf9276fc8bc.png)

**Comment by AllenBW** [comment]
So lets talk about what this actually is/means/needs to look like.  Input so an admin can adjust values? Just displaying them in an aside? @stackus @mafernando   Talk it out let me know and your collective will shall be executed.

**Comment by mafernando** [comment]
Think this is already being addressed by an extension @stackus is working on.

Closing for now.
