### ISSUE TITLE
Refactor ProjectQuestionsController from an F on Code Climate

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#844]
https://codeclimate.com/repos/551958df69568055c00020f8/ProjectQuestionsController

**Comment by mafernando** [comment]
Refactored from an F to a B. 

Closing for now. 

If we want to make this an A we'll need to figure out why the following method:
 
```ruby
def sort
    params[:position].each_with_index do |id, index|
      ProjectQuestion.where(id: id).update_all(position: index + 1)
    end

    respond_with project_questions
  end
```

Contributes so highly to the overall complexity score of the controller.
