### ISSUE TITLE
Create a new user type, Project Manager

### ISSUE THREAD

**Issue by Christine-Kim** [projectjellyfish/api#846]
In addition to User and Admin, create a new PM user type with different views? Would like this user to have a different display in the main Dashboard section, perhaps with more/different project, users, funding, usage trends and history widgets? Also would have access to a number of different projects, but not all.

**Comment by stackus** [comment]
Going to add a 'Manager' access type onto staff to cover this. Along with the new access type. I'll also add a new 'Manage' sidebar item and move content related sidebar items from admin to 'Manage'.

Creating a new issue for the Dashboard changes.

**Comment by sonejah21** [comment]
JEL-27
