### ISSUE TITLE
Updated "User" and "Admin" view

### ISSUE THREAD

**Issue by Christine-Kim** [projectjellyfish/api#847]
Currently, the view for user is identical to the admin view. Need to have more differentiated views to demonstrate custom user privileges and control. In addition to have the Admin menu show up for admins, having a different types of metrics/widgets show up on the main dashboard, more around service and health, alerts, and etc.? As a user, you should only have access to a handful of projects, and the dashboard should provide a summary of those projects.

**Comment by chriskacerguis** [comment]
Currently, in the system you only see the projects that you have access to.  So, an "admin" would see everything, but a user would only see the projects that they have access on.

What are some charts an admin would want that a user wouldn't?

**Comment by Christine-Kim** [comment]
As a user, I currently cannot create new projects. It gives me a server error. I seem to be able to create projects as an admin though, which is fine. Ideally, only the PMs and Admins should be able to create projects. Once a user is assigned to a project by a PM/admin, they can access those specific projects. So, on the User's dashboard, I'd imagine seeing something like (not in any particular order or priority - just ideas): Last time logged in, list of services they created, list of projects they're assigned to, status of those services and projects in terms of PoP ending, uptime, perhaps cost, and etc. 

As a PM, my dashboard should look very similar to what we currently have, but at the project level. I'd probably want to see the length of each project, remaining funding for each, average monthly charges (we already have), users, and etc. 

I'd imagine for the Admin view, perhaps more service health related metrics.

**Comment by AllenBW** [comment]
oh oh oh oh oh you bring up a great point.  if you're a user, cannot create projects, the button should appear as disabled.  thanks for listing chart suggestions! starring this for followup when that time (dashboard time) comes round

**Comment by chriskacerguis** [comment]
FYI. Users should be able to create projects

**Comment by AllenBW** [comment]
its the darn weirdest thing, when logged in as an admin, project creates just fine, when as a user we get an "unprocessable entry" due to missing the param `group_ids`.  weird thing is we don't require them for creating a project... one adds groups after a project is created...

so in the project_controller.rb we see
```
  def create
    authorize Project
    group_ids = current_user.admin? ? params[:group_ids] : params.require(:group_ids)
    project = Project.create project_params.merge(group_ids: group_ids)
    respond_with_params project
  end
```

which explains why  we are getting the error, if you're not an admin you are required to submit a group id... 

@stackus  or @mafernando   looking for what to do here, do we want to pull in and submit the user role along with creating a project?  or is this line leftover?

**Comment by AllenBW** [comment]
For @Christine-Kim  reference (and others), we moved this discussion #853

**Comment by sonejah21** [comment]
JEL-29
