### ISSUE TITLE
'Cancel' does not work on New Product page

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#852]
Clicking cancel doesn't work. When you click it nothing happens and no errors appear.

**Comment by AllenBW** [comment]
did you check from the pr branch? (what I am presently on, it works just fine)

**Comment by stackus** [comment]
Nope, tested on heroku dev.

**Comment by AllenBW** [comment]
sweet! well it'll be fixed with that one the :+1:  :smile:
