### ISSUE TITLE
Have UX reflect staff access level in some way.

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#853]
There should be some visual cue to the access level you're currently logged in with. Ideas include colors, messaging, dashboard changes.

"Would like this user to have a different display in the main Dashboard section, perhaps with more/different project, users, funding, usage trends and history widgets?"

Some ideas for the dashboard.

- User: See project status information for my projects, maybe a graph
- Manager: See health, and status for all projects. See content update reporting
- Admin: See application health, security alerts, i.e. failed logins, locked accounts.

**Comment by stackus** [comment]
This ticket is going to require some discussion before work should begin. Please put here your thoughts on additions/changes.

**Comment by AllenBW** [comment]
We also have the user page profile page to build out (on which we should specify the user roles, groups they belong to, all dem cool deets) , but I understand the goal of this discussion is to explore how we can at a glance differentiate different roles. 

Existing differentiation implemented, admin nav item on the left bar, what if we accent its absence by accenting its presence through the use of color, make it something that stands out as something unique to that user.  Heck we could do this for all specialty states(e.g. states the lowest user doesn't have access to)

**Comment by sonejah21** [comment]
JEL-28
