### ISSUE TITLE
bundle install jf user

### ISSUE THREAD

**Issue by alpha00Zero** [projectjellyfish/api#854]
so I ran through the documentation again and I cant run bundle install in the api directory as the jf user

**Comment by chriskacerguis** [comment]
Hello @alpha00Zero 

What is the error message that you are getting?

**Comment by alpha00Zero** [comment]
jellyfish@ip-x.x.x.x api]$ bundle install
bash: bundle: command not found

**Comment by stackus** [comment]
Sounds like the documentation may be missing a `gem install bundler` command, or it might be out of order.

**Comment by chriskacerguis** [comment]
Nope, I checked the docs, it is right here:

https://github.com/projectjellyfish/api/blob/master/docs/INSTALL-RHEL.md#install-bundler

@alpha00Zero My guess is that some steps got missed.

Chris

**Comment by alpha00Zero** [comment]
Sweet thanks Chris
