### ISSUE TITLE
API should be more strict about what params it accepts

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#855]
Talking with Allen about archiving projects made me realize that having a single `*_params` method to access permitted params is not going to cut it. Two common cases for different allowed params exist, `create` and `update`. We should also consider the action and the user making the call.

- [ ] Break `*_params` into `create_*_params` and `update_*_params`. This should be done for the majority of cases.
- [ ] Consider object state when allowing parameters when updating.
    - An example would be not allowing project attributes to be updated after it has been archived
- [x] Use [Pundits strong parameters helper][strong-params] `permitted_parameters` to further filter allowed values based on user access levels or relation to the object

This contest repo takes an interesting approach to the first two bullet points: https://github.com/sb8244/railschallenge-city-watch

[strong-params]: https://github.com/elabs/pundit#strong-parameters

**Comment by sonejah21** [comment]
JEL-30
