### ISSUE TITLE
Restore Alert Badges in App Nav

### ISSUE THREAD

**Issue by AllenBW** [projectjellyfish/api#859]
Lower right of user photo there used to be a badge indicating the number of outstanding alerts..
![capture](https://cloud.githubusercontent.com/assets/6640236/8832138/2cb1fb80-3075-11e5-8cef-7ecabdf9f3ea.PNG)

In efforts to restore this we need to talk about/build a consensus around which alerts to display, in this location.

Totally open to a new system also possibly one that displays the count of multiple alerts of varying types.

**Comment by sonejah21** [comment]
JEL-31
