### ISSUE TITLE
Demo Data : Data needs some aligning

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#863]
Some on the data in the demo data does not make sense. Budget alerts exist for projects with full budgets. Statuses and alerts sometimes don't line up.

- [x] Change the alerts or project details to line up so that they make sense
- [x] Align project status with the the alerts (Is there missing business logic?)

**Comment by mafernando** [comment]
Should be addressed by https://github.com/projectjellyfish/api/pull/873.

**Comment by mafernando** [comment]
Merged. Closing.
