### ISSUE TITLE
Pages need back functionality

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#866]
Sections or places that you 'drill down into' should have a back link. An example of a page like this would be the services details page.

- [x] Enumerate the pages that need back links
- [x] Create `back-link` directive
- [x] Develop UX for `back-link`, this includes determining placement on pages
- [x] Add `back-link` to pages

**Comment by AllenBW** [comment]
organized by state bulletined items are the state required the back button, root isthe desired destination of the back button

### projects.details
- order history
- service details

### services.list
- service details

### marketplace
- products.details

### admin.products
- product.details
