### ISSUE TITLE
List pages should have filtering and pagination

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#867]
List pages can be expected to display a lot of data. Filtering should be added so user can quickly find the data they want. Pagination should be added to limit the amount of data requested and displayed at one time.

- [ ] UX Designs for the filtering control and pagination
- [ ] API changes to support filtering searches and returning paginated results
- [ ] Investigate sorting and filtering server-side.

**Comment by AllenBW** [comment]
using smart table filtering and client side pagination? (if server side is desired we can just rewire the existing support)  

or did you have a different idea for how it might appear?

**Comment by stackus** [comment]
Appearance is item 1.

**Comment by sonejah21** [comment]
JEL-32
