### ISSUE TITLE
Use Markdown for the MOTD

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#868]
MOTD should use markdown to allow for formatting.

**Comment by AllenBW** [comment]
specifically markdown rather than html?

**Comment by stackus** [comment]
Yes.

**Comment by AllenBW** [comment]
you down with using this? https://github.com/btford/angular-markdown-directive 

alternatively we can just include showdown.js and custom roll a directive

**Comment by mafernando** [comment]
@AllenBW - I have some work done in this space on this https://github.com/projectjellyfish/api/pull/861.

We're using the angular-marked directive which makes things easier.

Let's hold off on this until the CMS UX is merged.

**Comment by AllenBW** [comment]
oh nice! sure thing, thanks for the heads up!

On Mon, Jul 27, 2015 at 11:32 AM, Michael Fernando <notifications@github.com

**Comment by mafernando** [comment]
One of these...

![image](https://cloud.githubusercontent.com/assets/9356425/8915824/e4a2292c-346c-11e5-8f54-64042343a982.png)

...is not like the other

![image](https://cloud.githubusercontent.com/assets/9356425/8915840/f9750126-346c-11e5-9e03-64023fdf9042.png)

Tasks:
- [ ] Removing the delete button 
- [ ] Add Markdown
- [ ] Apply styling to match other forms

**Comment by mafernando** [comment]
Additional Task:
- [ ] API/UX for MOTD Save on Edit does not sync up - needs to be fixed

**Comment by mafernando** [comment]
Addressed in PR https://github.com/projectjellyfish/api/pull/883.

**Comment by mafernando** [comment]
PR Merged. Closing.
