### ISSUE TITLE
Styling on the Roles pages are not inline with the rest of UX

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#869]
The roles pages need their styles fixed.

- [x] List page table is missing border
- [x] List page actions are missing the 'Action' heading
- [x] List page actions are not spaced correctly
- [x] List page table applies a hover effect as you move over rows
- [x] Role form checkboxes are not using the correct native repalcement
- [x] Role form checkboxes are backwards (Should be box then label)

**Comment by AllenBW** [comment]
Saved for tuesday!
