### ISSUE TITLE
Styling on the User (and other admin lists) pages are not inline with the rest of UX 

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#870]
The User pages need their styling fixed

- [x] User list table is missing its border
- [x] User list table has a 'filtering' box heading
- [x] User list table should display fewer columns. ID, Phone, Last Updated should be removed.
- [x] 'First/Last' column should just be 'Name' and names should be displayed as FirstName LastName
- [x] User list table columns are missing sortable UI. Name, Email, Role should be sortable

**Comment by AllenBW** [comment]
a little creep, but went ahead and brought the rest of admin tables up to style snuff on this ticket
