### ISSUE TITLE
jellyfish aws env variables

### ISSUE THREAD

**Issue by alpha00Zero** [projectjellyfish/api#882]
I'm trying to connect jellyfish to AWS for a quick demo.  I need to be able to provision a couple of ec2 instances.  I tried exporting AWS_ACCESS_KEY_ID,
AWS_SECRET_ACCESS_KEY.  I'm not getting an error but I still can "see" the AWS env.

**Comment by mafernando** [comment]
@alpha00Zero - can you run `rails c` from the `/api` directory and then execute `Rails.env` and provide the output?

```
C02MW21AFD59:api michaelfernando$ rails c
Loading development environment (Rails 4.2.3)
[1] pry(main)> Rails.env
=> "development"
```

I common issue I've encountered is that the rails server is not configured to run as production.

Fog.io (underling API used to provision) is configured to run in mock mode unless the server is production.

**Comment by alpha00Zero** [comment]
[jellyfish@ip-10-1-64-189 api]$ rails c

Loading test environment (Rails 4.2.3)

[1] pry(main)> *Rails*.env

=> *"*test*"*

[2] pry(main)>

On Tue, Jul 28, 2015 at 10:45 AM, Michael Fernando <notifications@github.com

**Comment by mafernando** [comment]
I think we identified an issue with the install guide.

![image](https://cloud.githubusercontent.com/assets/9356425/8939939/ebcd66ce-352c-11e5-9bfd-60528a90d13d.png)

Instead of echoing out `RAILS_ENV=test` into your bash profile, please use:

`echo 'export RAILS_ENV=production' >> ~/.bash_profile`

Then restart the server and verify that you are running in production and that Fog is not in mock mode:

```
C02MW21AFD59:api michaelfernando$ rails c
[1] pry(main)> Rails.env
=> "production"
[1] pry(main)> Fog.mock?
=> "false"
```

Let me know what happens when you restart the server as production and verify Fog.

**Comment by alpha00Zero** [comment]
I don’t know if running that command introduced a new issue or if the misconfiguration is the cause a new error.  I ran on another box and got the same message

[jellyfish@ip-10-1-67-238 api]$ rake db:migrate
rake aborted!
Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = 'f3f4b833b9364f80a194c136678650737a6d1954730c59944562e58aa830e33cb3a45039dfea906c5fc74fd8ee60c0d2adc8e65d4b7396cb1ecf024895822654'

Please ensure you restarted your application after installing Devise or setting the key.
/home/jellyfish/api/config/routes.rb:7:in `block (2 levels) in <top (required)>'
/home/jellyfish/api/config/routes.rb:5:in `block in <top (required)>'
/home/jellyfish/api/config/routes.rb:1:in `<top (required)>'
/home/jellyfish/api/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => environment

**Comment by mafernando** [comment]
I had issues with getting the environment vars in my bash profile to register with rails and found that using a `.env` file to set environment vars allowed me to sidestep those issues. 

See option 2 below:
![image](https://cloud.githubusercontent.com/assets/9356425/9067198/ae126d78-3aa1-11e5-9c2a-7d78db1ffdd6.png)

Make sure you have a `.env` file in your `\api` directory that contains:
- `DEVISE_SECRET_KEY=random`
- `SECRET_KEY_BASE=random`
- `DATABASE_URL=postgres://jellyfish:JELLYFISH_DB_PASSWORD@localhost:5432/jellyfish_production`
- `RAILS_ENV=production`
- `RACK_ENV=production`
- `JELLYFISH_MOCK_FOG=false`
- `JELLYFISH_AWS_ACCESS_KEY_ID=secret`
- `JELLYFISH_AWS_SECRET_ACCESS_KEY=token`

Then trying running the rake migrate command and see if it still errors out.

If you still encounter issues here, let me know.

**Comment by alpha00Zero** [comment]
I ran into the same issue earlier so I'm redeployment with the env file.

**Comment by mafernando** [comment]
Closing per @chriskacerguis.
