### ISSUE TITLE
Heroku Deploy button issues

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#888]
User states that the deploy to heroku button is still not working.  User states that when they to go the UX they get a white screen, and IE 10 reports that it is just "loading".

**Comment by LudovicBethune** [comment]
i created the #884 , i confirm that it works fine now and jellyfish is up and running but it takes 4 times to achieve to build process. For unknown reason the "run scripts & dyno..." failed 3 times.

**Comment by chriskacerguis** [comment]
Hello @LudovicBethune,

Yeah, the Heroku button is pretty buggy still (it's on their end).  We are probably going to remove it, and suggest people use Docker (or we are in the process of creating an AWS AMI)
