### ISSUE TITLE
Page icons need their color and sizes fixed

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#894]
<img width="335" alt="screen shot 2015-08-11 at 9 03 15 pm" src="https://cloud.githubusercontent.com/assets/158579/9215205/01662eb2-406d-11e5-9158-7c0ec86be037.png">

Added the icons into branch `feature/pages-sidenav-icons` but they're the wrong size and the colors do not match the normal and selected of the other icons.

Branch needs to be updated with correct icons.

**Comment by sonejah21** [comment]
Not sure why "Pages" isn't listed at all in the sidenav while in this ```feature/pages-sidenav-icons``` branch. 

I have edited the size thus far and pushed up. Will edit opacity once I can test it out.

**Comment by stackus** [comment]
resolved
