### ISSUE TITLE
can't transition from demo

### ISSUE THREAD

**Issue by spam4kev** [projectjellyfish/api#900]
I posted this describing the situation but haven't heard back.

http://talk.projectjellyfish.org/t/how-to-tie-in-manageiq-after-building-jellyfish/49

**Comment by chriskacerguis** [comment]
Hello,

Sorry for the delay in responding.  Please take a look here and let me know if you have any questions:

http://projectjellyfish.readthedocs.org/en/latest/how-tos/setup-manageiq/
