### ISSUE TITLE
Adding EC2 Instance - Subnet Error

### ISSUE THREAD

**Issue by jplatorre** [projectjellyfish/api#927]
When we try to add a new AWS instance under Add Product we get the following error:
*Subnet::UnauthorizedOperation - You are not authorized to perform this operation.*

AWS Secret Key has been added and we are logged into Jellyfish as Admin.

Any ideas on how to resolve?

![](https://i.gyazo.com/15fbb2dd6d8c0b524e80e667d0cb4384.png)

![](https://i.gyazo.com/57b2233d93984e235ae245251d41eb14.png)

**Comment by stackus** [comment]
You'll want to be sure the id and secret have been entered correctly. Also make sure the user has been given a policy permitting access to make calls regarding EC2 or CloudFormation. Try giving the user the policy `AmazonEC2FullAccess` and see if that solves the issue.

**Comment by chriskacerguis** [comment]
Closing ticket due to no response.
