### ISSUE TITLE
Clicking on 'Projects' or 'Order History' Produces 422 error page

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#938]
Upon pulling down the latest from jellyfish 'api' and running the following commands...
* bower install
* bundle install
* gulp build
* rake db:setup
* rake db:seed
* rake sample:demo
* rails s

I get an error page when I click on either 'Projects' or on 'Order History' in the sidebar. The error page is: "422 Unprocessable Entry" located at localhost:3000/error.

**Comment by voxlol** [comment]
Unable to reproduce
