### ISSUE TITLE
Login Screen needs manual URL editing in order to login

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#939]
The login screen remains stuck with username and password entered into fields until manually removing the `/login` from the URL.

After removing the '/login', it takes you to the dashboard and works just fine. 

See the attached video demonstrating this issue.

**Comment by chriskacerguis** [comment]
Nothing was in the console.
To reproduce...
login into DEV SERVER first

then try to login to TEST SERVER

(it should not redirect at that point)

**Comment by AllenBW** [comment]
Oh i totally noticed this! On it....
