### ISSUE TITLE
Move notifications back into API

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#951]
Notifications should be brought into core and the existing jellyfish-notification gem needs to be decommissioned.

An error occurs when provision gets executed and a notification gets generated:
<ArgumentError: Missing host to link to! Please provide the :host parameter, set default_url_options:host, or set :only_path to true>

**Comment by mafernando** [comment]
Assigning to myself to implement.

**Comment by mafernando** [comment]
Wisper hooks exist in the following controllers:
- `orders_controller.rb`
- `project_approvals_controller.rb`
- `projects_controller.rb`

**Comment by mafernando** [comment]
**Things To Do:** 
- decouple `jellyfish-notification gem` from API, basically remove it from the Gemfile
- add a listener to API that implements handlers for selected Wisper publications 
 - implement a mailer (extend ActionMailer) to construct and send new mail
   - this will require views for plaintext and html notifications 
 - NEED A WAY TO STORE SMTP CREDS
   - @stackus, since we've moved away from using  Dotenv, would it make sense to include this as part of a default notifications provider in API?
- subscribe to the aforementioned listener using a Rails initializer

**Comment by stackus** [comment]
Jellyfish provides a `Setting` feature, right now there's a pair of core settings already being defined.

https://github.com/projectjellyfish/api/blob/master/app/models/setting/core.rb

**Comment by mafernando** [comment]
Cool, I'm happy to use `Setting`s.

However, the SMTP settings will include things, like the API key for Postmark, which probably shouldn't be hardcoded. 

E.g. (username/password is the Postmark API key) https://github.com/projectjellyfish/jellyfish-notification/blob/master/config/initializers/application.rb#L5-L10

Any suggestions on how I should handle those?

**Comment by mafernando** [comment]
Working from [this](https://github.com/projectjellyfish/api/tree/feature/move-notifications-into-core) branch.

Currently fleshing out the implementation of the handler for project create notifications. Then will visit order and project approvals.

**Comment by mafernando** [comment]
Encountered some issues with a persistent: `ArguementError: A copy of <Listener> has been removed from the module tree but is still active!` issue which led me to [this](https://stackoverflow.com/questions/28346609/reload-wisper-listeners-automatically-at-every-request/28362286#28362286) link which fixed the issue.

**Comment by stackus** [comment]
Do you mean you were having issues saving to the database? Or do you mean that the application would bark out these errors after you modified a file and then made a request in development?

**Comment by mafernando** [comment]
When I tried to save a project create, the Wisper callback would bark out that error when trying to run the method I had defined in the listener. Its fixed now.

Working on figuring out the right way to set the ActionMailer SMTP settings now.

**Comment by mafernando** [comment]
For implementation, please see PR https://github.com/projectjellyfish/api/pull/1070.

**Comment by mafernando** [comment]
This issue is closed now.
