### ISSUE TITLE
Services Wizard final modal screen should have some text

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#957]
This ticket is for the Service wizard. Go to Projects > select an approved project > click "Add Service" button > Select Wizard at top right.

After completing all of the questions in the wizard modal, the final screen of the modal is too short compared to the others, and only shows you a button. 

Proposed Changes:
- Modal size should be larger in final screen. (This should come naturally with added wording.)
- The final modal screen should include some text saying that you have completed the wizard.
For example:  "Congratulations! The Wizard has come up with the best Service options for you. [button]" - or - "The Wizard has refined your search results to match your requirements [button]".

**Comment by sonejah21** [comment]
See #929 - https://github.com/projectjellyfish/api/pull/929
