### ISSUE TITLE
Creation of New Project without mandatory fields fails to show all issues

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#963]
Creation of a New Project page is not show all mandatory fields in red when you hit submit. Although, further submissions are disabled until all fields have been filled out, the UI doesn't display the mandatory fields any more.

**Comment by chriskacerguis** [comment]
FYI - This issue may have been fixed, need to confirm.

**Comment by voxlol** [comment]
can't reproduce the issue
