### ISSUE TITLE
Overhaul User Form

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#969]
- [ ] rework user confirmation to asynchronously compare
- [x] update staff resource for default user (used on create)
- [x] breakup create and edit states to match other forms
- [x] rework update and save to behave in the same manner as other forms

**Comment by voxlol** [comment]
Having issues with form placeholders and getting a dropdown menu to work after moving the user-forms to use the formprovider. Any suggestions?

**Comment by voxlol** [comment]
Closing this issue, see #1035 for the last bullet point
